import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';


@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {

    const city = [
      { label: 'KAB MALUKU TENGGARA BARAT', value: { id: '8103', name: 'KAB MALUKU TENGGARA BARAT', idprov: '81' } },
      { label: 'KAB PEGUNUNGAN BINTANG', value: { id: '9112', name: 'KAB PEGUNUNGAN BINTANG', idprov: '91' } },
      { label: 'KAB TIMOR TENGAH SELATAN', value: { id: '5302', name: 'KAB TIMOR TENGAH SELATAN', idprov: '53' } },
      { label: 'KAB. ACEH BARAT', value: { id: '1105', name: 'KAB. ACEH BARAT', idprov: '11' } },
      { label: 'KAB. ACEH BARAT DAYA', value: { id: '1112', name: 'KAB. ACEH BARAT DAYA', idprov: '11' } },
      { label: 'KAB. ACEH BESAR', value: { id: '1106', name: 'KAB. ACEH BESAR', idprov: '11' } },
      { label: 'KAB. ACEH JAYA', value: { id: '1114', name: 'KAB. ACEH JAYA', idprov: '11' } },
      { label: 'KAB. ACEH SELATAN', value: { id: '1101', name: 'KAB. ACEH SELATAN', idprov: '11' } },
      { label: 'KAB. ACEH SINGKIL', value: { id: '1110', name: 'KAB. ACEH SINGKIL', idprov: '11' } },
      { label: 'KAB. ACEH TAMIANG', value: { id: '1116', name: 'KAB. ACEH TAMIANG', idprov: '11' } },
      { label: 'KAB. ACEH TENGAH', value: { id: '1104', name: 'KAB. ACEH TENGAH', idprov: '11' } },
      { label: 'KAB. ACEH TENGGARA', value: { id: '1102', name: 'KAB. ACEH TENGGARA', idprov: '11' } },
      { label: 'KAB. ACEH TIMUR', value: { id: '1103', name: 'KAB. ACEH TIMUR', idprov: '11' } },
      { label: 'KAB. ACEH UTARA', value: { id: '1108', name: 'KAB. ACEH UTARA', idprov: '11' } },
      { label: 'KAB. ADM. KEP. SERIBU', value: { id: '3101', name: 'KAB. ADM. KEP. SERIBU', idprov: '31' } },
      { label: 'KAB. AGAM', value: { id: '1306', name: 'KAB. AGAM', idprov: '13' } },
      { label: 'KAB. ALOR', value: { id: '5305', name: 'KAB. ALOR', idprov: '53' } },
      { label: 'KAB. ASAHAN', value: { id: '1209', name: 'KAB. ASAHAN', idprov: '12' } },
      { label: 'KAB. ASMAT', value: { id: '9118', name: 'KAB. ASMAT', idprov: '91' } },
      { label: 'KAB. BADUNG', value: { id: '5103', name: 'KAB. BADUNG', idprov: '51' } },
      { label: 'KAB. BALANGAN', value: { id: '6311', name: 'KAB. BALANGAN', idprov: '63' } },
      { label: 'KAB. BANDUNG', value: { id: '3204', name: 'KAB. BANDUNG', idprov: '32' } },
      { label: 'KAB. BANDUNG BARAT', value: { id: '3217', name: 'KAB. BANDUNG BARAT', idprov: '32' } },
      { label: 'KAB. BANGGAI', value: { id: '7201', name: 'KAB. BANGGAI', idprov: '72' } },
      { label: 'KAB. BANGGAI KEPULAUAN', value: { id: '7207', name: 'KAB. BANGGAI KEPULAUAN', idprov: '72' } },
      { label: 'KAB. BANGGAI LAUT', value: { id: '7211', name: 'KAB. BANGGAI LAUT', idprov: '72' } },
      { label: 'KAB. BANGKA', value: { id: '1901', name: 'KAB. BANGKA', idprov: '19' } },
      { label: 'KAB. BANGKA BARAT', value: { id: '1905', name: 'KAB. BANGKA BARAT', idprov: '19' } },
      { label: 'KAB. BANGKA SELATAN', value: { id: '1903', name: 'KAB. BANGKA SELATAN', idprov: '19' } },
      { label: 'KAB. BANGKA TENGAH', value: { id: '1904', name: 'KAB. BANGKA TENGAH', idprov: '19' } },
      { label: 'KAB. BANGKALAN', value: { id: '3526', name: 'KAB. BANGKALAN', idprov: '35' } },
      { label: 'KAB. BANGLI', value: { id: '5106', name: 'KAB. BANGLI', idprov: '51' } },
      { label: 'KAB. BANJAR', value: { id: '6303', name: 'KAB. BANJAR', idprov: '63' } },
      { label: 'KAB. BANJARNEGARA', value: { id: '3304', name: 'KAB. BANJARNEGARA', idprov: '33' } },
      { label: 'KAB. BANTAENG', value: { id: '7303', name: 'KAB. BANTAENG', idprov: '73' } },
      { label: 'KAB. BANTUL', value: { id: '3402', name: 'KAB. BANTUL', idprov: '34' } },
      { label: 'KAB. BANYUASIN', value: { id: '1607', name: 'KAB. BANYUASIN', idprov: '16' } },
      { label: 'KAB. BANYUMAS', value: { id: '3302', name: 'KAB. BANYUMAS', idprov: '33' } },
      { label: 'KAB. BANYUWANGI', value: { id: '3510', name: 'KAB. BANYUWANGI', idprov: '35' } },
      { label: 'KAB. BARITO KUALA', value: { id: '6304', name: 'KAB. BARITO KUALA', idprov: '63' } },
      { label: 'KAB. BARITO SELATAN', value: { id: '6204', name: 'KAB. BARITO SELATAN', idprov: '62' } },
      { label: 'KAB. BARITO TIMUR', value: { id: '6213', name: 'KAB. BARITO TIMUR', idprov: '62' } },
      { label: 'KAB. BARITO UTARA', value: { id: '6205', name: 'KAB. BARITO UTARA', idprov: '62' } },
      { label: 'KAB. BARRU', value: { id: '7311', name: 'KAB. BARRU', idprov: '73' } },
      { label: 'KAB. BATANG', value: { id: '3325', name: 'KAB. BATANG', idprov: '33' } },
      { label: 'KAB. BATANGHARI', value: { id: '1504', name: 'KAB. BATANGHARI', idprov: '15' } },
      { label: 'KAB. BATU BARA', value: { id: '1219', name: 'KAB. BATU BARA', idprov: '12' } },
      { label: 'KAB. BEKASI', value: { id: '3216', name: 'KAB. BEKASI', idprov: '32' } },
      { label: 'KAB. BELITUNG', value: { id: '1902', name: 'KAB. BELITUNG', idprov: '19' } },
      { label: 'KAB. BELITUNG TIMUR', value: { id: '1906', name: 'KAB. BELITUNG TIMUR', idprov: '19' } },
      { label: 'KAB. BELU', value: { id: '5304', name: 'KAB. BELU', idprov: '53' } },
      { label: 'KAB. BENER MERIAH', value: { id: '1117', name: 'KAB. BENER MERIAH', idprov: '11' } },
      { label: 'KAB. BENGKALIS', value: { id: '1403', name: 'KAB. BENGKALIS', idprov: '14' } },
      { label: 'KAB. BENGKAYANG', value: { id: '6107', name: 'KAB. BENGKAYANG', idprov: '61' } },
      { label: 'KAB. BENGKULU SELATAN', value: { id: '1701', name: 'KAB. BENGKULU SELATAN', idprov: '17' } },
      { label: 'KAB. BENGKULU TENGAH', value: { id: '1709', name: 'KAB. BENGKULU TENGAH', idprov: '17' } },
      { label: 'KAB. BENGKULU UTARA', value: { id: '1703', name: 'KAB. BENGKULU UTARA', idprov: '17' } },
      { label: 'KAB. BERAU', value: { id: '6403', name: 'KAB. BERAU', idprov: '64' } },
      { label: 'KAB. BIAK NUMFOR', value: { id: '9106', name: 'KAB. BIAK NUMFOR', idprov: '91' } },
      { label: 'KAB. BIMA', value: { id: '5206', name: 'KAB. BIMA', idprov: '52' } },
      { label: 'KAB. BINTAN', value: { id: '2101', name: 'KAB. BINTAN', idprov: '21' } },
      { label: 'KAB. BIREUEN', value: { id: '1111', name: 'KAB. BIREUEN', idprov: '11' } },
      { label: 'KAB. BLITAR', value: { id: '3505', name: 'KAB. BLITAR', idprov: '35' } },
      { label: 'KAB. BLORA', value: { id: '3316', name: 'KAB. BLORA', idprov: '33' } },
      { label: 'KAB. BOALEMO', value: { id: '7502', name: 'KAB. BOALEMO', idprov: '75' } },
      { label: 'KAB. BOGOR', value: { id: '3201', name: 'KAB. BOGOR', idprov: '32' } },
      { label: 'KAB. BOJONEGORO', value: { id: '3522', name: 'KAB. BOJONEGORO', idprov: '35' } },
      { label: 'KAB. BOLAANG MONGONDOW', value: { id: '7101', name: 'KAB. BOLAANG MONGONDOW', idprov: '71' } },
      { label: 'KAB. BOLAANG MONGONDOW SELATAN', value: { id: '7111', name: 'KAB. BOLAANG MONGONDOW SELATAN', idprov: '71' } },
      { label: 'KAB. BOLAANG MONGONDOW TIMUR', value: { id: '7110', name: 'KAB. BOLAANG MONGONDOW TIMUR', idprov: '71' } },
      { label: 'KAB. BOLAANG MONGONDOW UTARA', value: { id: '7108', name: 'KAB. BOLAANG MONGONDOW UTARA', idprov: '71' } },
      { label: 'KAB. BOMBANA', value: { id: '7406', name: 'KAB. BOMBANA', idprov: '74' } },
      { label: 'KAB. BONDOWOSO', value: { id: '3511', name: 'KAB. BONDOWOSO', idprov: '35' } },
      { label: 'KAB. BONE', value: { id: '7308', name: 'KAB. BONE', idprov: '73' } },
      { label: 'KAB. BONE BOLANGO', value: { id: '7503', name: 'KAB. BONE BOLANGO', idprov: '75' } },
      { label: 'KAB. BOVEN DIGOEL', value: { id: '9116', name: 'KAB. BOVEN DIGOEL', idprov: '91' } },
      { label: 'KAB. BOYOLALI', value: { id: '3309', name: 'KAB. BOYOLALI', idprov: '33' } },
      { label: 'KAB. BREBES', value: { id: '3329', name: 'KAB. BREBES', idprov: '33' } },
      { label: 'KAB. BULELENG', value: { id: '5108', name: 'KAB. BULELENG', idprov: '51' } },
      { label: 'KAB. BULUKUMBA', value: { id: '7302', name: 'KAB. BULUKUMBA', idprov: '73' } },
      { label: 'KAB. BULUNGAN', value: { id: '6501', name: 'KAB. BULUNGAN', idprov: '65' } },
      { label: 'KAB. BUNGO', value: { id: '1508', name: 'KAB. BUNGO', idprov: '15' } },
      { label: 'KAB. BUOL', value: { id: '7205', name: 'KAB. BUOL', idprov: '72' } },
      { label: 'KAB. BURU', value: { id: '8104', name: 'KAB. BURU', idprov: '81' } },
      { label: 'KAB. BURU SELATAN', value: { id: '8109', name: 'KAB. BURU SELATAN', idprov: '81' } },
      { label: 'KAB. BUTON', value: { id: '7404', name: 'KAB. BUTON', idprov: '74' } },
      { label: 'KAB. BUTON SELATAN', value: { id: '7415', name: 'KAB. BUTON SELATAN', idprov: '74' } },
      { label: 'KAB. BUTON TENGAH', value: { id: '7414', name: 'KAB. BUTON TENGAH', idprov: '74' } },
      { label: 'KAB. BUTON UTARA', value: { id: '7410', name: 'KAB. BUTON UTARA', idprov: '74' } },
      { label: 'KAB. CIAMIS', value: { id: '3207', name: 'KAB. CIAMIS', idprov: '32' } },
      { label: 'KAB. CIANJUR', value: { id: '3203', name: 'KAB. CIANJUR', idprov: '32' } },
      { label: 'KAB. CILACAP', value: { id: '3301', name: 'KAB. CILACAP', idprov: '33' } },
      { label: 'KAB. CIREBON', value: { id: '3209', name: 'KAB. CIREBON', idprov: '32' } },
      { label: 'KAB. DAIRI', value: { id: '1211', name: 'KAB. DAIRI', idprov: '12' } },
      { label: 'KAB. DEIYAI', value: { id: '9128', name: 'KAB. DEIYAI', idprov: '91' } },
      { label: 'KAB. DELI SERDANG', value: { id: '1207', name: 'KAB. DELI SERDANG', idprov: '12' } },
      { label: 'KAB. DEMAK', value: { id: '3321', name: 'KAB. DEMAK', idprov: '33' } },
      { label: 'KAB. DHARMASRAYA', value: { id: '1310', name: 'KAB. DHARMASRAYA', idprov: '13' } },
      { label: 'KAB. DOGIYAI', value: { id: '9126', name: 'KAB. DOGIYAI', idprov: '91' } },
      { label: 'KAB. DOMPU', value: { id: '5205', name: 'KAB. DOMPU', idprov: '52' } },
      { label: 'KAB. DONGGALA', value: { id: '7203', name: 'KAB. DONGGALA', idprov: '72' } },
      { label: 'KAB. EMPAT LAWANG', value: { id: '1611', name: 'KAB. EMPAT LAWANG', idprov: '16' } },
      { label: 'KAB. ENDE', value: { id: '5308', name: 'KAB. ENDE', idprov: '53' } },
      { label: 'KAB. ENREKANG', value: { id: '7316', name: 'KAB. ENREKANG', idprov: '73' } },
      { label: 'KAB. FAK FAK', value: { id: '9203', name: 'KAB. FAK FAK', idprov: '92' } },
      { label: 'KAB. FLORES TIMUR', value: { id: '5306', name: 'KAB. FLORES TIMUR', idprov: '53' } },
      { label: 'KAB. GARUT', value: { id: '3205', name: 'KAB. GARUT', idprov: '32' } },
      { label: 'KAB. GAYO LUES', value: { id: '1113', name: 'KAB. GAYO LUES', idprov: '11' } },
      { label: 'KAB. GIANYAR', value: { id: '5104', name: 'KAB. GIANYAR', idprov: '51' } },
      { label: 'KAB. GORONTALO', value: { id: '7501', name: 'KAB. GORONTALO', idprov: '75' } },
      { label: 'KAB. GORONTALO UTARA', value: { id: '7505', name: 'KAB. GORONTALO UTARA', idprov: '75' } },
      { label: 'KAB. GOWA', value: { id: '7306', name: 'KAB. GOWA', idprov: '73' } },
      { label: 'KAB. GRESIK', value: { id: '3525', name: 'KAB. GRESIK', idprov: '35' } },
      { label: 'KAB. GROBOGAN', value: { id: '3315', name: 'KAB. GROBOGAN', idprov: '33' } },
      { label: 'KAB. GUNUNG KIDUL', value: { id: '3403', name: 'KAB. GUNUNG KIDUL', idprov: '34' } },
      { label: 'KAB. GUNUNG MAS', value: { id: '6210', name: 'KAB. GUNUNG MAS', idprov: '62' } },
      { label: 'KAB. HALMAHERA BARAT', value: { id: '8201', name: 'KAB. HALMAHERA BARAT', idprov: '82' } },
      { label: 'KAB. HALMAHERA SELATAN', value: { id: '8204', name: 'KAB. HALMAHERA SELATAN', idprov: '82' } },
      { label: 'KAB. HALMAHERA TENGAH', value: { id: '8202', name: 'KAB. HALMAHERA TENGAH', idprov: '82' } },
      { label: 'KAB. HALMAHERA TIMUR', value: { id: '8206', name: 'KAB. HALMAHERA TIMUR', idprov: '82' } },
      { label: 'KAB. HALMAHERA UTARA', value: { id: '8203', name: 'KAB. HALMAHERA UTARA', idprov: '82' } },
      { label: 'KAB. HULU SUNGAI SELATAN', value: { id: '6306', name: 'KAB. HULU SUNGAI SELATAN', idprov: '63' } },
      { label: 'KAB. HULU SUNGAI TENGAH', value: { id: '6307', name: 'KAB. HULU SUNGAI TENGAH', idprov: '63' } },
      { label: 'KAB. HULU SUNGAI UTARA', value: { id: '6308', name: 'KAB. HULU SUNGAI UTARA', idprov: '63' } },
      { label: 'KAB. HUMBANG HASUNDUTAN', value: { id: '1216', name: 'KAB. HUMBANG HASUNDUTAN', idprov: '12' } },
      { label: 'KAB. INDRAGIRI HILIR', value: { id: '1404', name: 'KAB. INDRAGIRI HILIR', idprov: '14' } },
      { label: 'KAB. INDRAGIRI HULU', value: { id: '1402', name: 'KAB. INDRAGIRI HULU', idprov: '14' } },
      { label: 'KAB. INDRAMAYU', value: { id: '3212', name: 'KAB. INDRAMAYU', idprov: '32' } },
      { label: 'KAB. INTAN JAYA', value: { id: '9127', name: 'KAB. INTAN JAYA', idprov: '91' } },
      { label: 'KAB. JAYAPURA', value: { id: '9103', name: 'KAB. JAYAPURA', idprov: '91' } },
      { label: 'KAB. JAYAWIJAYA', value: { id: '9102', name: 'KAB. JAYAWIJAYA', idprov: '91' } },
      { label: 'KAB. JEMBER', value: { id: '3509', name: 'KAB. JEMBER', idprov: '35' } },
      { label: 'KAB. JEMBRANA', value: { id: '5101', name: 'KAB. JEMBRANA', idprov: '51' } },
      { label: 'KAB. JENEPONTO', value: { id: '7304', name: 'KAB. JENEPONTO', idprov: '73' } },
      { label: 'KAB. JEPARA', value: { id: '3320', name: 'KAB. JEPARA', idprov: '33' } },
      { label: 'KAB. JOMBANG', value: { id: '3517', name: 'KAB. JOMBANG', idprov: '35' } },
      { label: 'KAB. KAIMANA', value: { id: '9208', name: 'KAB. KAIMANA', idprov: '92' } },
      { label: 'KAB. KAMPAR', value: { id: '1401', name: 'KAB. KAMPAR', idprov: '14' } },
      { label: 'KAB. KAPUAS', value: { id: '6203', name: 'KAB. KAPUAS', idprov: '62' } },
      { label: 'KAB. KAPUAS HULU', value: { id: '6106', name: 'KAB. KAPUAS HULU', idprov: '61' } },
      { label: 'KAB. KARANGANYAR', value: { id: '3313', name: 'KAB. KARANGANYAR', idprov: '33' } },
      { label: 'KAB. KARANGASEM', value: { id: '5107', name: 'KAB. KARANGASEM', idprov: '51' } },
      { label: 'KAB. KARAWANG', value: { id: '3215', name: 'KAB. KARAWANG', idprov: '32' } },
      { label: 'KAB. KARIMUN', value: { id: '2102', name: 'KAB. KARIMUN', idprov: '21' } },
      { label: 'KAB. KARO', value: { id: '1206', name: 'KAB. KARO', idprov: '12' } },
      { label: 'KAB. KATINGAN', value: { id: '6206', name: 'KAB. KATINGAN', idprov: '62' } },
      { label: 'KAB. KAUR', value: { id: '1704', name: 'KAB. KAUR', idprov: '17' } },
      { label: 'KAB. KAYONG UTARA', value: { id: '6111', name: 'KAB. KAYONG UTARA', idprov: '61' } },
      { label: 'KAB. KEBUMEN', value: { id: '3305', name: 'KAB. KEBUMEN', idprov: '33' } },
      { label: 'KAB. KEDIRI', value: { id: '3506', name: 'KAB. KEDIRI', idprov: '35' } },
      { label: 'KAB. KEEROM', value: { id: '9111', name: 'KAB. KEEROM', idprov: '91' } },
      { label: 'KAB. KENDAL', value: { id: '3324', name: 'KAB. KENDAL', idprov: '33' } },
      { label: 'KAB. KEP. SIAU TAGULANDANG BIARO', value: { id: '7109', name: 'KAB. KEP. SIAU TAGULANDANG BIARO', idprov: '71' } },
      { label: 'KAB. KEPAHIANG', value: { id: '1708', name: 'KAB. KEPAHIANG', idprov: '17' } },
      { label: 'KAB. KEPULAUAN ANAMBAS', value: { id: '2105', name: 'KAB. KEPULAUAN ANAMBAS', idprov: '21' } },
      { label: 'KAB. KEPULAUAN ARU', value: { id: '8107', name: 'KAB. KEPULAUAN ARU', idprov: '81' } },
      { label: 'KAB. KEPULAUAN MENTAWAI', value: { id: '1309', name: 'KAB. KEPULAUAN MENTAWAI', idprov: '13' } },
      { label: 'KAB. KEPULAUAN MERANTI', value: { id: '1410', name: 'KAB. KEPULAUAN MERANTI', idprov: '14' } },
      { label: 'KAB. KEPULAUAN SANGIHE', value: { id: '7103', name: 'KAB. KEPULAUAN SANGIHE', idprov: '71' } },
      { label: 'KAB. KEPULAUAN SELAYAR', value: { id: '7301', name: 'KAB. KEPULAUAN SELAYAR', idprov: '73' } },
      { label: 'KAB. KEPULAUAN SULA', value: { id: '8205', name: 'KAB. KEPULAUAN SULA', idprov: '82' } },
      { label: 'KAB. KEPULAUAN TALAUD', value: { id: '7104', name: 'KAB. KEPULAUAN TALAUD', idprov: '71' } },
      { label: 'KAB. KEPULAUAN YAPEN', value: { id: '9105', name: 'KAB. KEPULAUAN YAPEN', idprov: '91' } },
      { label: 'KAB. KERINCI', value: { id: '1501', name: 'KAB. KERINCI', idprov: '15' } },
      { label: 'KAB. KETAPANG', value: { id: '6104', name: 'KAB. KETAPANG', idprov: '61' } },
      { label: 'KAB. KLATEN', value: { id: '3310', name: 'KAB. KLATEN', idprov: '33' } },
      { label: 'KAB. KLUNGKUNG', value: { id: '5105', name: 'KAB. KLUNGKUNG', idprov: '51' } },
      { label: 'KAB. KOLAKA', value: { id: '7401', name: 'KAB. KOLAKA', idprov: '74' } },
      { label: 'KAB. KOLAKA TIMUR', value: { id: '7411', name: 'KAB. KOLAKA TIMUR', idprov: '74' } },
      { label: 'KAB. KOLAKA UTARA', value: { id: '7408', name: 'KAB. KOLAKA UTARA', idprov: '74' } },
      { label: 'KAB. KONAWE', value: { id: '7402', name: 'KAB. KONAWE', idprov: '74' } },
      { label: 'KAB. KONAWE KEPULAUAN', value: { id: '7412', name: 'KAB. KONAWE KEPULAUAN', idprov: '74' } },
      { label: 'KAB. KONAWE SELATAN', value: { id: '7405', name: 'KAB. KONAWE SELATAN', idprov: '74' } },
      { label: 'KAB. KONAWE UTARA', value: { id: '7409', name: 'KAB. KONAWE UTARA', idprov: '74' } },
      { label: 'KAB. KOTABARU', value: { id: '6302', name: 'KAB. KOTABARU', idprov: '63' } },
      { label: 'KAB. KOTAWARINGIN BARAT', value: { id: '6201', name: 'KAB. KOTAWARINGIN BARAT', idprov: '62' } },
      { label: 'KAB. KOTAWARINGIN TIMUR', value: { id: '6202', name: 'KAB. KOTAWARINGIN TIMUR', idprov: '62' } },
      { label: 'KAB. KUANTAN SINGINGI', value: { id: '1409', name: 'KAB. KUANTAN SINGINGI', idprov: '14' } },
      { label: 'KAB. KUBU RAYA', value: { id: '6112', name: 'KAB. KUBU RAYA', idprov: '61' } },
      { label: 'KAB. KUDUS', value: { id: '3319', name: 'KAB. KUDUS', idprov: '33' } },
      { label: 'KAB. KULON PROGO', value: { id: '3401', name: 'KAB. KULON PROGO', idprov: '34' } },
      { label: 'KAB. KUNINGAN', value: { id: '3208', name: 'KAB. KUNINGAN', idprov: '32' } },
      { label: 'KAB. KUPANG', value: { id: '5301', name: 'KAB. KUPANG', idprov: '53' } },
      { label: 'KAB. KUTAI BARAT', value: { id: '6407', name: 'KAB. KUTAI BARAT', idprov: '64' } },
      { label: 'KAB. KUTAI KARTANEGARA', value: { id: '6402', name: 'KAB. KUTAI KARTANEGARA', idprov: '64' } },
      { label: 'KAB. KUTAI TIMUR', value: { id: '6408', name: 'KAB. KUTAI TIMUR', idprov: '64' } },
      { label: 'KAB. LABUHANBATU', value: { id: '1210', name: 'KAB. LABUHANBATU', idprov: '12' } },
      { label: 'KAB. LABUHANBATU SELATAN', value: { id: '1222', name: 'KAB. LABUHANBATU SELATAN', idprov: '12' } },
      { label: 'KAB. LABUHANBATU UTARA', value: { id: '1223', name: 'KAB. LABUHANBATU UTARA', idprov: '12' } },
      { label: 'KAB. LAHAT', value: { id: '1604', name: 'KAB. LAHAT', idprov: '16' } },
      { label: 'KAB. LAMANDAU', value: { id: '6209', name: 'KAB. LAMANDAU', idprov: '62' } },
      { label: 'KAB. LAMONGAN', value: { id: '3524', name: 'KAB. LAMONGAN', idprov: '35' } },
      { label: 'KAB. LAMPUNG BARAT', value: { id: '1804', name: 'KAB. LAMPUNG BARAT', idprov: '18' } },
      { label: 'KAB. LAMPUNG SELATAN', value: { id: '1801', name: 'KAB. LAMPUNG SELATAN', idprov: '18' } },
      { label: 'KAB. LAMPUNG TENGAH', value: { id: '1802', name: 'KAB. LAMPUNG TENGAH', idprov: '18' } },
      { label: 'KAB. LAMPUNG TIMUR', value: { id: '1807', name: 'KAB. LAMPUNG TIMUR', idprov: '18' } },
      { label: 'KAB. LAMPUNG UTARA', value: { id: '1803', name: 'KAB. LAMPUNG UTARA', idprov: '18' } },
      { label: 'KAB. LANDAK', value: { id: '6108', name: 'KAB. LANDAK', idprov: '61' } },
      { label: 'KAB. LANGKAT', value: { id: '1205', name: 'KAB. LANGKAT', idprov: '12' } },
      { label: 'KAB. LANNY JAYA', value: { id: '9123', name: 'KAB. LANNY JAYA', idprov: '91' } },
      { label: 'KAB. LEBAK', value: { id: '3602', name: 'KAB. LEBAK', idprov: '36' } },
      { label: 'KAB. LEBONG', value: { id: '1707', name: 'KAB. LEBONG', idprov: '17' } },
      { label: 'KAB. LEMBATA', value: { id: '5313', name: 'KAB. LEMBATA', idprov: '53' } },
      { label: 'KAB. LIMA PULUH KOTA', value: { id: '1307', name: 'KAB. LIMA PULUH KOTA', idprov: '13' } },
      { label: 'KAB. LINGGA', value: { id: '2104', name: 'KAB. LINGGA', idprov: '21' } },
      { label: 'KAB. LOMBOK BARAT', value: { id: '5201', name: 'KAB. LOMBOK BARAT', idprov: '52' } },
      { label: 'KAB. LOMBOK TENGAH', value: { id: '5202', name: 'KAB. LOMBOK TENGAH', idprov: '52' } },
      { label: 'KAB. LOMBOK TIMUR', value: { id: '5203', name: 'KAB. LOMBOK TIMUR', idprov: '52' } },
      { label: 'KAB. LOMBOK UTARA', value: { id: '5208', name: 'KAB. LOMBOK UTARA', idprov: '52' } },
      { label: 'KAB. LUMAJANG', value: { id: '3508', name: 'KAB. LUMAJANG', idprov: '35' } },
      { label: 'KAB. LUWU', value: { id: '7317', name: 'KAB. LUWU', idprov: '73' } },
      { label: 'KAB. LUWU TIMUR', value: { id: '7324', name: 'KAB. LUWU TIMUR', idprov: '73' } },
      { label: 'KAB. LUWU UTARA', value: { id: '7322', name: 'KAB. LUWU UTARA', idprov: '73' } },
      { label: 'KAB. MADIUN', value: { id: '3519', name: 'KAB. MADIUN', idprov: '35' } },
      { label: 'KAB. MAGELANG', value: { id: '3308', name: 'KAB. MAGELANG', idprov: '33' } },
      { label: 'KAB. MAGETAN', value: { id: '3520', name: 'KAB. MAGETAN', idprov: '35' } },
      { label: 'KAB. MAHAKAM ULU', value: { id: '6411', name: 'KAB. MAHAKAM ULU', idprov: '64' } },
      { label: 'KAB. MAJALENGKA', value: { id: '3210', name: 'KAB. MAJALENGKA', idprov: '32' } },
      { label: 'KAB. MAJENE', value: { id: '7605', name: 'KAB. MAJENE', idprov: '76' } },
      { label: 'KAB. MALAKA', value: { id: '5321', name: 'KAB. MALAKA', idprov: '53' } },
      { label: 'KAB. MALANG', value: { id: '3507', name: 'KAB. MALANG', idprov: '35' } },
      { label: 'KAB. MALINAU', value: { id: '6502', name: 'KAB. MALINAU', idprov: '65' } },
      { label: 'KAB. MALUKU BARAT DAYA', value: { id: '8108', name: 'KAB. MALUKU BARAT DAYA', idprov: '81' } },
      { label: 'KAB. MALUKU TENGAH', value: { id: '8101', name: 'KAB. MALUKU TENGAH', idprov: '81' } },
      { label: 'KAB. MALUKU TENGGARA', value: { id: '8102', name: 'KAB. MALUKU TENGGARA', idprov: '81' } },
      { label: 'KAB. MAMASA', value: { id: '7603', name: 'KAB. MAMASA', idprov: '76' } },
      { label: 'KAB. MAMBERAMO RAYA', value: { id: '9120', name: 'KAB. MAMBERAMO RAYA', idprov: '91' } },
      { label: 'KAB. MAMBERAMO TENGAH', value: { id: '9121', name: 'KAB. MAMBERAMO TENGAH', idprov: '91' } },
      { label: 'KAB. MAMUJU', value: { id: '7602', name: 'KAB. MAMUJU', idprov: '76' } },
      { label: 'KAB. MAMUJU TENGAH', value: { id: '7606', name: 'KAB. MAMUJU TENGAH', idprov: '76' } },
      { label: 'KAB. MAMUJU UTARA', value: { id: '7601', name: 'KAB. MAMUJU UTARA', idprov: '76' } },
      { label: 'KAB. MANDAILING NATAL', value: { id: '1213', name: 'KAB. MANDAILING NATAL', idprov: '12' } },
      { label: 'KAB. MANGGARAI', value: { id: '5310', name: 'KAB. MANGGARAI', idprov: '53' } },
      { label: 'KAB. MANGGARAI BARAT', value: { id: '5315', name: 'KAB. MANGGARAI BARAT', idprov: '53' } },
      { label: 'KAB. MANGGARAI TIMUR', value: { id: '5319', name: 'KAB. MANGGARAI TIMUR', idprov: '53' } },
      { label: 'KAB. MANOKWARI', value: { id: '9202', name: 'KAB. MANOKWARI', idprov: '92' } },
      { label: 'KAB. MANOKWARI SELATAN', value: { id: '9211', name: 'KAB. MANOKWARI SELATAN', idprov: '92' } },
      { label: 'KAB. MAPPI', value: { id: '9117', name: 'KAB. MAPPI', idprov: '91' } },
      { label: 'KAB. MAROS', value: { id: '7309', name: 'KAB. MAROS', idprov: '73' } },
      { label: 'KAB. MAYBRAT', value: { id: '9210', name: 'KAB. MAYBRAT', idprov: '92' } },
      { label: 'KAB. MELAWI', value: { id: '6110', name: 'KAB. MELAWI', idprov: '61' } },
      { label: 'KAB. MEMPAWAH', value: { id: '6102', name: 'KAB. MEMPAWAH', idprov: '61' } },
      { label: 'KAB. MERANGIN', value: { id: '1502', name: 'KAB. MERANGIN', idprov: '15' } },
      { label: 'KAB. MERAUKE', value: { id: '9101', name: 'KAB. MERAUKE', idprov: '91' } },
      { label: 'KAB. MESUJI', value: { id: '1811', name: 'KAB. MESUJI', idprov: '18' } },
      { label: 'KAB. MIMIKA', value: { id: '9109', name: 'KAB. MIMIKA', idprov: '91' } },
      { label: 'KAB. MINAHASA', value: { id: '7102', name: 'KAB. MINAHASA', idprov: '71' } },
      { label: 'KAB. MINAHASA SELATAN', value: { id: '7105', name: 'KAB. MINAHASA SELATAN', idprov: '71' } },
      { label: 'KAB. MINAHASA TENGGARA', value: { id: '7107', name: 'KAB. MINAHASA TENGGARA', idprov: '71' } },
      { label: 'KAB. MINAHASA UTARA', value: { id: '7106', name: 'KAB. MINAHASA UTARA', idprov: '71' } },
      { label: 'KAB. MOJOKERTO', value: { id: '3516', name: 'KAB. MOJOKERTO', idprov: '35' } },
      { label: 'KAB. MOROWALI', value: { id: '7206', name: 'KAB. MOROWALI', idprov: '72' } },
      { label: 'KAB. MOROWALI UTARA', value: { id: '7212', name: 'KAB. MOROWALI UTARA', idprov: '72' } },
      { label: 'KAB. MUARA ENIM', value: { id: '1603', name: 'KAB. MUARA ENIM', idprov: '16' } },
      { label: 'KAB. MUARO JAMBI', value: { id: '1505', name: 'KAB. MUARO JAMBI', idprov: '15' } },
      { label: 'KAB. MUKO MUKO', value: { id: '1706', name: 'KAB. MUKO MUKO', idprov: '17' } },
      { label: 'KAB. MUNA', value: { id: '7403', name: 'KAB. MUNA', idprov: '74' } },
      { label: 'KAB. MUNA BARAT', value: { id: '7413', name: 'KAB. MUNA BARAT', idprov: '74' } },
      { label: 'KAB. MURUNG RAYA', value: { id: '6212', name: 'KAB. MURUNG RAYA', idprov: '62' } },
      { label: 'KAB. MUSI BANYUASIN', value: { id: '1606', name: 'KAB. MUSI BANYUASIN', idprov: '16' } },
      { label: 'KAB. MUSI RAWAS', value: { id: '1605', name: 'KAB. MUSI RAWAS', idprov: '16' } },
      { label: 'KAB. MUSI RAWAS UTARA', value: { id: '1613', name: 'KAB. MUSI RAWAS UTARA', idprov: '16' } },
      { label: 'KAB. NABIRE', value: { id: '9104', name: 'KAB. NABIRE', idprov: '91' } },
      { label: 'KAB. NAGAN RAYA', value: { id: '1115', name: 'KAB. NAGAN RAYA', idprov: '11' } },
      { label: 'KAB. NAGEKEO', value: { id: '5316', name: 'KAB. NAGEKEO', idprov: '53' } },
      { label: 'KAB. NATUNA', value: { id: '2103', name: 'KAB. NATUNA', idprov: '21' } },
      { label: 'KAB. NDUGA', value: { id: '9124', name: 'KAB. NDUGA', idprov: '91' } },
      { label: 'KAB. NGADA', value: { id: '5309', name: 'KAB. NGADA', idprov: '53' } },
      { label: 'KAB. NGANJUK', value: { id: '3518', name: 'KAB. NGANJUK', idprov: '35' } },
      { label: 'KAB. NGAWI', value: { id: '3521', name: 'KAB. NGAWI', idprov: '35' } },
      { label: 'KAB. NIAS', value: { id: '1204', name: 'KAB. NIAS', idprov: '12' } },
      { label: 'KAB. NIAS BARAT', value: { id: '1225', name: 'KAB. NIAS BARAT', idprov: '12' } },
      { label: 'KAB. NIAS SELATAN', value: { id: '1214', name: 'KAB. NIAS SELATAN', idprov: '12' } },
      { label: 'KAB. NIAS UTARA', value: { id: '1224', name: 'KAB. NIAS UTARA', idprov: '12' } },
      { label: 'KAB. NUNUKAN', value: { id: '6503', name: 'KAB. NUNUKAN', idprov: '65' } },
      { label: 'KAB. OGAN ILIR', value: { id: '1610', name: 'KAB. OGAN ILIR', idprov: '16' } },
      { label: 'KAB. OGAN KOMERING ILIR', value: { id: '1602', name: 'KAB. OGAN KOMERING ILIR', idprov: '16' } },
      { label: 'KAB. OGAN KOMERING ULU', value: { id: '1601', name: 'KAB. OGAN KOMERING ULU', idprov: '16' } },
      { label: 'KAB. OGAN KOMERING ULU SELATAN', value: { id: '1609', name: 'KAB. OGAN KOMERING ULU SELATAN', idprov: '16' } },
      { label: 'KAB. OGAN KOMERING ULU TIMUR', value: { id: '1608', name: 'KAB. OGAN KOMERING ULU TIMUR', idprov: '16' } },
      { label: 'KAB. PACITAN', value: { id: '3501', name: 'KAB. PACITAN', idprov: '35' } },
      { label: 'KAB. PADANG LAWAS', value: { id: '1221', name: 'KAB. PADANG LAWAS', idprov: '12' } },
      { label: 'KAB. PADANG LAWAS UTARA', value: { id: '1220', name: 'KAB. PADANG LAWAS UTARA', idprov: '12' } },
      { label: 'KAB. PADANG PARIAMAN', value: { id: '1305', name: 'KAB. PADANG PARIAMAN', idprov: '13' } },
      { label: 'KAB. PAHUWATO', value: { id: '7504', name: 'KAB. PAHUWATO', idprov: '75' } },
      { label: 'KAB. PAKPAK BHARAT', value: { id: '1215', name: 'KAB. PAKPAK BHARAT', idprov: '12' } },
      { label: 'KAB. PAMEKASAN', value: { id: '3528', name: 'KAB. PAMEKASAN', idprov: '35' } },
      { label: 'KAB. PANDEGLANG', value: { id: '3601', name: 'KAB. PANDEGLANG', idprov: '36' } },
      { label: 'KAB. PANGANDARAN', value: { id: '3218', name: 'KAB. PANGANDARAN', idprov: '32' } },
      { label: 'KAB. PANGKAJENE KEPULAUAN', value: { id: '7310', name: 'KAB. PANGKAJENE KEPULAUAN', idprov: '73' } },
      { label: 'KAB. PANIAI', value: { id: '9108', name: 'KAB. PANIAI', idprov: '91' } },
      { label: 'KAB. PARIGI MOUTONG', value: { id: '7208', name: 'KAB. PARIGI MOUTONG', idprov: '72' } },
      { label: 'KAB. PASAMAN', value: { id: '1308', name: 'KAB. PASAMAN', idprov: '13' } },
      { label: 'KAB. PASAMAN BARAT', value: { id: '1312', name: 'KAB. PASAMAN BARAT', idprov: '13' } },
      { label: 'KAB. PASER', value: { id: '6401', name: 'KAB. PASER', idprov: '64' } },
      { label: 'KAB. PASURUAN', value: { id: '3514', name: 'KAB. PASURUAN', idprov: '35' } },
      { label: 'KAB. PATI', value: { id: '3318', name: 'KAB. PATI', idprov: '33' } },
      { label: 'KAB. PEGUNUNGAN ARFAK', value: { id: '9212', name: 'KAB. PEGUNUNGAN ARFAK', idprov: '92' } },
      { label: 'KAB. PEKALONGAN', value: { id: '3326', name: 'KAB. PEKALONGAN', idprov: '33' } },
      { label: 'KAB. PELALAWAN', value: { id: '1405', name: 'KAB. PELALAWAN', idprov: '14' } },
      { label: 'KAB. PEMALANG', value: { id: '3327', name: 'KAB. PEMALANG', idprov: '33' } },
      { label: 'KAB. PENAJAM PASER UTARA', value: { id: '6409', name: 'KAB. PENAJAM PASER UTARA', idprov: '64' } },
      { label: 'KAB. PENUKAL ABAB LEMATANG ILIR', value: { id: '1612', name: 'KAB. PENUKAL ABAB LEMATANG ILIR', idprov: '16' } },
      { label: 'KAB. PESAWARAN', value: { id: '1809', name: 'KAB. PESAWARAN', idprov: '18' } },
      { label: 'KAB. PESISIR BARAT', value: { id: '1813', name: 'KAB. PESISIR BARAT', idprov: '18' } },
      { label: 'KAB. PESISIR SELATAN', value: { id: '1301', name: 'KAB. PESISIR SELATAN', idprov: '13' } },
      { label: 'KAB. PIDIE', value: { id: '1107', name: 'KAB. PIDIE', idprov: '11' } },
      { label: 'KAB. PIDIE JAYA', value: { id: '1118', name: 'KAB. PIDIE JAYA', idprov: '11' } },
      { label: 'KAB. PINRANG', value: { id: '7315', name: 'KAB. PINRANG', idprov: '73' } },
      { label: 'KAB. POLEWALI MANDAR', value: { id: '7604', name: 'KAB. POLEWALI MANDAR', idprov: '76' } },
      { label: 'KAB. PONOROGO', value: { id: '3502', name: 'KAB. PONOROGO', idprov: '35' } },
      { label: 'KAB. POSO', value: { id: '7202', name: 'KAB. POSO', idprov: '72' } },
      { label: 'KAB. PRINGSEWU', value: { id: '1810', name: 'KAB. PRINGSEWU', idprov: '18' } },
      { label: 'KAB. PROBOLINGGO', value: { id: '3513', name: 'KAB. PROBOLINGGO', idprov: '35' } },
      { label: 'KAB. PULANG PISAU', value: { id: '6211', name: 'KAB. PULANG PISAU', idprov: '62' } },
      { label: 'KAB. PULAU MOROTAI', value: { id: '8207', name: 'KAB. PULAU MOROTAI', idprov: '82' } },
      { label: 'KAB. PULAU TALIABU', value: { id: '8208', name: 'KAB. PULAU TALIABU', idprov: '82' } },
      { label: 'KAB. PUNCAK', value: { id: '9125', name: 'KAB. PUNCAK', idprov: '91' } },
      { label: 'KAB. PUNCAK JAYA', value: { id: '9107', name: 'KAB. PUNCAK JAYA', idprov: '91' } },
      { label: 'KAB. PURBALINGGA', value: { id: '3303', name: 'KAB. PURBALINGGA', idprov: '33' } },
      { label: 'KAB. PURWAKARTA', value: { id: '3214', name: 'KAB. PURWAKARTA', idprov: '32' } },
      { label: 'KAB. PURWOREJO', value: { id: '3306', name: 'KAB. PURWOREJO', idprov: '33' } },
      { label: 'KAB. RAJA AMPAT', value: { id: '9205', name: 'KAB. RAJA AMPAT', idprov: '92' } },
      { label: 'KAB. REJANG LEBONG', value: { id: '1702', name: 'KAB. REJANG LEBONG', idprov: '17' } },
      { label: 'KAB. REMBANG', value: { id: '3317', name: 'KAB. REMBANG', idprov: '33' } },
      { label: 'KAB. ROKAN HILIR', value: { id: '1407', name: 'KAB. ROKAN HILIR', idprov: '14' } },
      { label: 'KAB. ROKAN HULU', value: { id: '1406', name: 'KAB. ROKAN HULU', idprov: '14' } },
      { label: 'KAB. ROTE NDAO', value: { id: '5314', name: 'KAB. ROTE NDAO', idprov: '53' } },
      { label: 'KAB. SABU RAIJUA', value: { id: '5320', name: 'KAB. SABU RAIJUA', idprov: '53' } },
      { label: 'KAB. SAMBAS', value: { id: '6101', name: 'KAB. SAMBAS', idprov: '61' } },
      { label: 'KAB. SAMOSIR', value: { id: '1217', name: 'KAB. SAMOSIR', idprov: '12' } },
      { label: 'KAB. SAMPANG', value: { id: '3527', name: 'KAB. SAMPANG', idprov: '35' } },
      { label: 'KAB. SANGGAU', value: { id: '6103', name: 'KAB. SANGGAU', idprov: '61' } },
      { label: 'KAB. SARMI', value: { id: '9110', name: 'KAB. SARMI', idprov: '91' } },
      { label: 'KAB. SAROLANGUN', value: { id: '1503', name: 'KAB. SAROLANGUN', idprov: '15' } },
      { label: 'KAB. SEKADAU', value: { id: '6109', name: 'KAB. SEKADAU', idprov: '61' } },
      { label: 'KAB. SELUMA', value: { id: '1705', name: 'KAB. SELUMA', idprov: '17' } },
      { label: 'KAB. SEMARANG', value: { id: '3322', name: 'KAB. SEMARANG', idprov: '33' } },
      { label: 'KAB. SERAM BAGIAN BARAT', value: { id: '8106', name: 'KAB. SERAM BAGIAN BARAT', idprov: '81' } },
      { label: 'KAB. SERAM BAGIAN TIMUR', value: { id: '8105', name: 'KAB. SERAM BAGIAN TIMUR', idprov: '81' } },
      { label: 'KAB. SERANG', value: { id: '3604', name: 'KAB. SERANG', idprov: '36' } },
      { label: 'KAB. SERDANG BEDAGAI', value: { id: '1218', name: 'KAB. SERDANG BEDAGAI', idprov: '12' } },
      { label: 'KAB. SERUYAN', value: { id: '6207', name: 'KAB. SERUYAN', idprov: '62' } },
      { label: 'KAB. SIAK', value: { id: '1408', name: 'KAB. SIAK', idprov: '14' } },
      { label: 'KAB. SIDENRENG RAPPANG', value: { id: '7314', name: 'KAB. SIDENRENG RAPPANG', idprov: '73' } },
      { label: 'KAB. SIDOARJO', value: { id: '3515', name: 'KAB. SIDOARJO', idprov: '35' } },
      { label: 'KAB. SIGI', value: { id: '7210', name: 'KAB. SIGI', idprov: '72' } },
      { label: 'KAB. SIJUNJUNG', value: { id: '1303', name: 'KAB. SIJUNJUNG', idprov: '13' } },
      { label: 'KAB. SIKKA', value: { id: '5307', name: 'KAB. SIKKA', idprov: '53' } },
      { label: 'KAB. SIMALUNGUN', value: { id: '1208', name: 'KAB. SIMALUNGUN', idprov: '12' } },
      { label: 'KAB. SIMEULUE', value: { id: '1109', name: 'KAB. SIMEULUE', idprov: '11' } },
      { label: 'KAB. SINJAI', value: { id: '7307', name: 'KAB. SINJAI', idprov: '73' } },
      { label: 'KAB. SINTANG', value: { id: '6105', name: 'KAB. SINTANG', idprov: '61' } },
      { label: 'KAB. SITUBONDO', value: { id: '3512', name: 'KAB. SITUBONDO', idprov: '35' } },
      { label: 'KAB. SLEMAN', value: { id: '3404', name: 'KAB. SLEMAN', idprov: '34' } },
      { label: 'KAB. SOLOK', value: { id: '1302', name: 'KAB. SOLOK', idprov: '13' } },
      { label: 'KAB. SOLOK SELATAN', value: { id: '1311', name: 'KAB. SOLOK SELATAN', idprov: '13' } },
      { label: 'KAB. SOPPENG', value: { id: '7312', name: 'KAB. SOPPENG', idprov: '73' } },
      { label: 'KAB. SORONG', value: { id: '9201', name: 'KAB. SORONG', idprov: '92' } },
      { label: 'KAB. SORONG SELATAN', value: { id: '9204', name: 'KAB. SORONG SELATAN', idprov: '92' } },
      { label: 'KAB. SRAGEN', value: { id: '3314', name: 'KAB. SRAGEN', idprov: '33' } },
      { label: 'KAB. SUBANG', value: { id: '3213', name: 'KAB. SUBANG', idprov: '32' } },
      { label: 'KAB. SUKABUMI', value: { id: '3202', name: 'KAB. SUKABUMI', idprov: '32' } },
      { label: 'KAB. SUKAMARA', value: { id: '6208', name: 'KAB. SUKAMARA', idprov: '62' } },
      { label: 'KAB. SUKOHARJO', value: { id: '3311', name: 'KAB. SUKOHARJO', idprov: '33' } },
      { label: 'KAB. SUMBA BARAT', value: { id: '5312', name: 'KAB. SUMBA BARAT', idprov: '53' } },
      { label: 'KAB. SUMBA BARAT DAYA', value: { id: '5318', name: 'KAB. SUMBA BARAT DAYA', idprov: '53' } },
      { label: 'KAB. SUMBA TENGAH', value: { id: '5317', name: 'KAB. SUMBA TENGAH', idprov: '53' } },
      { label: 'KAB. SUMBA TIMUR', value: { id: '5311', name: 'KAB. SUMBA TIMUR', idprov: '53' } },
      { label: 'KAB. SUMBAWA', value: { id: '5204', name: 'KAB. SUMBAWA', idprov: '52' } },
      { label: 'KAB. SUMBAWA BARAT', value: { id: '5207', name: 'KAB. SUMBAWA BARAT', idprov: '52' } },
      { label: 'KAB. SUMEDANG', value: { id: '3211', name: 'KAB. SUMEDANG', idprov: '32' } },
      { label: 'KAB. SUMENEP', value: { id: '3529', name: 'KAB. SUMENEP', idprov: '35' } },
      { label: 'KAB. SUPIORI', value: { id: '9119', name: 'KAB. SUPIORI', idprov: '91' } },
      { label: 'KAB. TABALONG', value: { id: '6309', name: 'KAB. TABALONG', idprov: '63' } },
      { label: 'KAB. TABANAN', value: { id: '5102', name: 'KAB. TABANAN', idprov: '51' } },
      { label: 'KAB. TAKALAR', value: { id: '7305', name: 'KAB. TAKALAR', idprov: '73' } },
      { label: 'KAB. TAMBRAUW', value: { id: '9209', name: 'KAB. TAMBRAUW', idprov: '92' } },
      { label: 'KAB. TANA TIDUNG', value: { id: '6504', name: 'KAB. TANA TIDUNG', idprov: '65' } },
      { label: 'KAB. TANA TORAJA', value: { id: '7318', name: 'KAB. TANA TORAJA', idprov: '73' } },
      { label: 'KAB. TANAH BUMBU', value: { id: '6310', name: 'KAB. TANAH BUMBU', idprov: '63' } },
      { label: 'KAB. TANAH DATAR', value: { id: '1304', name: 'KAB. TANAH DATAR', idprov: '13' } },
      { label: 'KAB. TANAH LAUT', value: { id: '6301', name: 'KAB. TANAH LAUT', idprov: '63' } },
      { label: 'KAB. TANGERANG', value: { id: '3603', name: 'KAB. TANGERANG', idprov: '36' } },
      { label: 'KAB. TANGGAMUS', value: { id: '1806', name: 'KAB. TANGGAMUS', idprov: '18' } },
      { label: 'KAB. TANJUNG JABUNG BARAT', value: { id: '1506', name: 'KAB. TANJUNG JABUNG BARAT', idprov: '15' } },
      { label: 'KAB. TANJUNG JABUNG TIMUR', value: { id: '1507', name: 'KAB. TANJUNG JABUNG TIMUR', idprov: '15' } },
      { label: 'KAB. TAPANULI SELATAN', value: { id: '1203', name: 'KAB. TAPANULI SELATAN', idprov: '12' } },
      { label: 'KAB. TAPANULI TENGAH', value: { id: '1201', name: 'KAB. TAPANULI TENGAH', idprov: '12' } },
      { label: 'KAB. TAPANULI UTARA', value: { id: '1202', name: 'KAB. TAPANULI UTARA', idprov: '12' } },
      { label: 'KAB. TAPIN', value: { id: '6305', name: 'KAB. TAPIN', idprov: '63' } },
      { label: 'KAB. TASIKMALAYA', value: { id: '3206', name: 'KAB. TASIKMALAYA', idprov: '32' } },
      { label: 'KAB. TEBO', value: { id: '1509', name: 'KAB. TEBO', idprov: '15' } },
      { label: 'KAB. TEGAL', value: { id: '3328', name: 'KAB. TEGAL', idprov: '33' } },
      { label: 'KAB. TELUK BINTUNI', value: { id: '9206', name: 'KAB. TELUK BINTUNI', idprov: '92' } },
      { label: 'KAB. TELUK WONDAMA', value: { id: '9207', name: 'KAB. TELUK WONDAMA', idprov: '92' } },
      { label: 'KAB. TEMANGGUNG', value: { id: '3323', name: 'KAB. TEMANGGUNG', idprov: '33' } },
      { label: 'KAB. TIMOR TENGAH UTARA', value: { id: '5303', name: 'KAB. TIMOR TENGAH UTARA', idprov: '53' } },
      { label: 'KAB. TOBA SAMOSIR', value: { id: '1212', name: 'KAB. TOBA SAMOSIR', idprov: '12' } },
      { label: 'KAB. TOJO UNA UNA', value: { id: '7209', name: 'KAB. TOJO UNA UNA', idprov: '72' } },
      { label: 'KAB. TOLI TOLI', value: { id: '7204', name: 'KAB. TOLI TOLI', idprov: '72' } },
      { label: 'KAB. TOLIKARA', value: { id: '9114', name: 'KAB. TOLIKARA', idprov: '91' } },
      { label: 'KAB. TORAJA UTARA', value: { id: '7326', name: 'KAB. TORAJA UTARA', idprov: '73' } },
      { label: 'KAB. TRENGGALEK', value: { id: '3503', name: 'KAB. TRENGGALEK', idprov: '35' } },
      { label: 'KAB. TUBAN', value: { id: '3523', name: 'KAB. TUBAN', idprov: '35' } },
      { label: 'KAB. TULANG BAWANG', value: { id: '1805', name: 'KAB. TULANG BAWANG', idprov: '18' } },
      { label: 'KAB. TULANG BAWANG BARAT', value: { id: '1812', name: 'KAB. TULANG BAWANG BARAT', idprov: '18' } },
      { label: 'KAB. TULUNGAGUNG', value: { id: '3504', name: 'KAB. TULUNGAGUNG', idprov: '35' } },
      { label: 'KAB. WAJO', value: { id: '7313', name: 'KAB. WAJO', idprov: '73' } },
      { label: 'KAB. WAKATOBI', value: { id: '7407', name: 'KAB. WAKATOBI', idprov: '74' } },
      { label: 'KAB. WAROPEN', value: { id: '9115', name: 'KAB. WAROPEN', idprov: '91' } },
      { label: 'KAB. WAY KANAN', value: { id: '1808', name: 'KAB. WAY KANAN', idprov: '18' } },
      { label: 'KAB. WONOGIRI', value: { id: '3312', name: 'KAB. WONOGIRI', idprov: '33' } },
      { label: 'KAB. WONOSOBO', value: { id: '3307', name: 'KAB. WONOSOBO', idprov: '33' } },
      { label: 'KAB. YAHUKIMO', value: { id: '9113', name: 'KAB. YAHUKIMO', idprov: '91' } },
      { label: 'KAB. YALIMO', value: { id: '9122', name: 'KAB. YALIMO', idprov: '91' } },
      { label: 'KOTA ADM. JAKARTA BARAT', value: { id: '3173', name: 'KOTA ADM. JAKARTA BARAT', idprov: '31' } },
      { label: 'KOTA ADM. JAKARTA PUSAT', value: { id: '3171', name: 'KOTA ADM. JAKARTA PUSAT', idprov: '31' } },
      { label: 'KOTA ADM. JAKARTA SELATAN', value: { id: '3174', name: 'KOTA ADM. JAKARTA SELATAN', idprov: '31' } },
      { label: 'KOTA ADM. JAKARTA TIMUR', value: { id: '3175', name: 'KOTA ADM. JAKARTA TIMUR', idprov: '31' } },
      { label: 'KOTA ADM. JAKARTA UTARA', value: { id: '3172', name: 'KOTA ADM. JAKARTA UTARA', idprov: '31' } },
      { label: 'KOTA AMBON', value: { id: '8171', name: 'KOTA AMBON', idprov: '81' } },
      { label: 'KOTA BALIKPAPAN', value: { id: '6471', name: 'KOTA BALIKPAPAN', idprov: '64' } },
      { label: 'KOTA BANDA ACEH', value: { id: '1171', name: 'KOTA BANDA ACEH', idprov: '11' } },
      { label: 'KOTA BANDAR LAMPUNG', value: { id: '1871', name: 'KOTA BANDAR LAMPUNG', idprov: '18' } },
      { label: 'KOTA BANDUNG', value: { id: '3273', name: 'KOTA BANDUNG', idprov: '32' } },
      { label: 'KOTA BANJAR', value: { id: '3279', name: 'KOTA BANJAR', idprov: '32' } },
      { label: 'KOTA BANJARBARU', value: { id: '6372', name: 'KOTA BANJARBARU', idprov: '63' } },
      { label: 'KOTA BANJARMASIN', value: { id: '6371', name: 'KOTA BANJARMASIN', idprov: '63' } },
      { label: 'KOTA BATAM', value: { id: '2171', name: 'KOTA BATAM', idprov: '21' } },
      { label: 'KOTA BATU', value: { id: '3579', name: 'KOTA BATU', idprov: '35' } },
      { label: 'KOTA BAU BAU', value: { id: '7472', name: 'KOTA BAU BAU', idprov: '74' } },
      { label: 'KOTA BEKASI', value: { id: '3275', name: 'KOTA BEKASI', idprov: '32' } },
      { label: 'KOTA BENGKULU', value: { id: '1771', name: 'KOTA BENGKULU', idprov: '17' } },
      { label: 'KOTA BIMA', value: { id: '5272', name: 'KOTA BIMA', idprov: '52' } },
      { label: 'KOTA BINJAI', value: { id: '1275', name: 'KOTA BINJAI', idprov: '12' } },
      { label: 'KOTA BITUNG', value: { id: '7172', name: 'KOTA BITUNG', idprov: '71' } },
      { label: 'KOTA BLITAR', value: { id: '3572', name: 'KOTA BLITAR', idprov: '35' } },
      { label: 'KOTA BOGOR', value: { id: '3271', name: 'KOTA BOGOR', idprov: '32' } },
      { label: 'KOTA BONTANG', value: { id: '6474', name: 'KOTA BONTANG', idprov: '64' } },
      { label: 'KOTA BUKITTINGGI', value: { id: '1375', name: 'KOTA BUKITTINGGI', idprov: '13' } },
      { label: 'KOTA CILEGON', value: { id: '3672', name: 'KOTA CILEGON', idprov: '36' } },
      { label: 'KOTA CIMAHI', value: { id: '3277', name: 'KOTA CIMAHI', idprov: '32' } },
      { label: 'KOTA CIREBON', value: { id: '3274', name: 'KOTA CIREBON', idprov: '32' } },
      { label: 'KOTA DENPASAR', value: { id: '5171', name: 'KOTA DENPASAR', idprov: '51' } },
      { label: 'KOTA DEPOK', value: { id: '3276', name: 'KOTA DEPOK', idprov: '32' } },
      { label: 'KOTA DUMAI', value: { id: '1472', name: 'KOTA DUMAI', idprov: '14' } },
      { label: 'KOTA GORONTALO', value: { id: '7571', name: 'KOTA GORONTALO', idprov: '75' } },
      { label: 'KOTA GUNUNGSITOLI', value: { id: '1278', name: 'KOTA GUNUNGSITOLI', idprov: '12' } },
      { label: 'KOTA JAMBI', value: { id: '1571', name: 'KOTA JAMBI', idprov: '15' } },
      { label: 'KOTA JAYAPURA', value: { id: '9171', name: 'KOTA JAYAPURA', idprov: '91' } },
      { label: 'KOTA KEDIRI', value: { id: '3571', name: 'KOTA KEDIRI', idprov: '35' } },
      { label: 'KOTA KENDARI', value: { id: '7471', name: 'KOTA KENDARI', idprov: '74' } },
      { label: 'KOTA KOTAMOBAGU', value: { id: '7174', name: 'KOTA KOTAMOBAGU', idprov: '71' } },
      { label: 'KOTA KUPANG', value: { id: '5371', name: 'KOTA KUPANG', idprov: '53' } },
      { label: 'KOTA LANGSA', value: { id: '1174', name: 'KOTA LANGSA', idprov: '11' } },
      { label: 'KOTA LHOKSEUMAWE', value: { id: '1173', name: 'KOTA LHOKSEUMAWE', idprov: '11' } },
      { label: 'KOTA LUBUK LINGGAU', value: { id: '1673', name: 'KOTA LUBUK LINGGAU', idprov: '16' } },
      { label: 'KOTA MADIUN', value: { id: '3577', name: 'KOTA MADIUN', idprov: '35' } },
      { label: 'KOTA MAGELANG', value: { id: '3371', name: 'KOTA MAGELANG', idprov: '33' } },
      { label: 'KOTA MAKASSAR', value: { id: '7371', name: 'KOTA MAKASSAR', idprov: '73' } },
      { label: 'KOTA MALANG', value: { id: '3573', name: 'KOTA MALANG', idprov: '35' } },
      { label: 'KOTA MANADO', value: { id: '7171', name: 'KOTA MANADO', idprov: '71' } },
      { label: 'KOTA MATARAM', value: { id: '5271', name: 'KOTA MATARAM', idprov: '52' } },
      { label: 'KOTA MEDAN', value: { id: '1271', name: 'KOTA MEDAN', idprov: '12' } },
      { label: 'KOTA METRO', value: { id: '1872', name: 'KOTA METRO', idprov: '18' } },
      { label: 'KOTA MOJOKERTO', value: { id: '3576', name: 'KOTA MOJOKERTO', idprov: '35' } },
      { label: 'KOTA PADANG', value: { id: '1371', name: 'KOTA PADANG', idprov: '13' } },
      { label: 'KOTA PADANG PANJANG', value: { id: '1374', name: 'KOTA PADANG PANJANG', idprov: '13' } },
      { label: 'KOTA PADANGSIDIMPUAN', value: { id: '1277', name: 'KOTA PADANGSIDIMPUAN', idprov: '12' } },
      { label: 'KOTA PAGAR ALAM', value: { id: '1672', name: 'KOTA PAGAR ALAM', idprov: '16' } },
      { label: 'KOTA PALANGKARAYA', value: { id: '6271', name: 'KOTA PALANGKARAYA', idprov: '62' } },
      { label: 'KOTA PALEMBANG', value: { id: '1671', name: 'KOTA PALEMBANG', idprov: '16' } },
      { label: 'KOTA PALOPO', value: { id: '7373', name: 'KOTA PALOPO', idprov: '73' } },
      { label: 'KOTA PALU', value: { id: '7271', name: 'KOTA PALU', idprov: '72' } },
      { label: 'KOTA PANGKAL PINANG', value: { id: '1971', name: 'KOTA PANGKAL PINANG', idprov: '19' } },
      { label: 'KOTA PARE PARE', value: { id: '7372', name: 'KOTA PARE PARE', idprov: '73' } },
      { label: 'KOTA PARIAMAN', value: { id: '1377', name: 'KOTA PARIAMAN', idprov: '13' } },
      { label: 'KOTA PASURUAN', value: { id: '3575', name: 'KOTA PASURUAN', idprov: '35' } },
      { label: 'KOTA PAYAKUMBUH', value: { id: '1376', name: 'KOTA PAYAKUMBUH', idprov: '13' } },
      { label: 'KOTA PEKALONGAN', value: { id: '3375', name: 'KOTA PEKALONGAN', idprov: '33' } },
      { label: 'KOTA PEKANBARU', value: { id: '1471', name: 'KOTA PEKANBARU', idprov: '14' } },
      { label: 'KOTA PEMATANG SIANTAR', value: { id: '1272', name: 'KOTA PEMATANG SIANTAR', idprov: '12' } },
      { label: 'KOTA PONTIANAK', value: { id: '6171', name: 'KOTA PONTIANAK', idprov: '61' } },
      { label: 'KOTA PRABUMULIH', value: { id: '1674', name: 'KOTA PRABUMULIH', idprov: '16' } },
      { label: 'KOTA PROBOLINGGO', value: { id: '3574', name: 'KOTA PROBOLINGGO', idprov: '35' } },
      { label: 'KOTA SABANG', value: { id: '1172', name: 'KOTA SABANG', idprov: '11' } },
      { label: 'KOTA SALATIGA', value: { id: '3373', name: 'KOTA SALATIGA', idprov: '33' } },
      { label: 'KOTA SAMARINDA', value: { id: '6472', name: 'KOTA SAMARINDA', idprov: '64' } },
      { label: 'KOTA SAWAHLUNTO', value: { id: '1373', name: 'KOTA SAWAHLUNTO', idprov: '13' } },
      { label: 'KOTA SEMARANG', value: { id: '3374', name: 'KOTA SEMARANG', idprov: '33' } },
      { label: 'KOTA SERANG', value: { id: '3673', name: 'KOTA SERANG', idprov: '36' } },
      { label: 'KOTA SIBOLGA', value: { id: '1273', name: 'KOTA SIBOLGA', idprov: '12' } },
      { label: 'KOTA SINGKAWANG', value: { id: '6172', name: 'KOTA SINGKAWANG', idprov: '61' } },
      { label: 'KOTA SOLOK', value: { id: '1372', name: 'KOTA SOLOK', idprov: '13' } },
      { label: 'KOTA SORONG', value: { id: '9271', name: 'KOTA SORONG', idprov: '92' } },
      { label: 'KOTA SUBULUSSALAM', value: { id: '1175', name: 'KOTA SUBULUSSALAM', idprov: '11' } },
      { label: 'KOTA SUKABUMI', value: { id: '3272', name: 'KOTA SUKABUMI', idprov: '32' } },
      { label: 'KOTA SUNGAI PENUH', value: { id: '1572', name: 'KOTA SUNGAI PENUH', idprov: '15' } },
      { label: 'KOTA SURABAYA', value: { id: '3578', name: 'KOTA SURABAYA', idprov: '35' } },
      { label: 'KOTA SURAKARTA', value: { id: '3372', name: 'KOTA SURAKARTA', idprov: '33' } },
      { label: 'KOTA TANGERANG', value: { id: '3671', name: 'KOTA TANGERANG', idprov: '36' } },
      { label: 'KOTA TANGERANG SELATAN', value: { id: '3674', name: 'KOTA TANGERANG SELATAN', idprov: '36' } },
      { label: 'KOTA TANJUNG BALAI', value: { id: '1274', name: 'KOTA TANJUNG BALAI', idprov: '12' } },
      { label: 'KOTA TANJUNG PINANG', value: { id: '2172', name: 'KOTA TANJUNG PINANG', idprov: '21' } },
      { label: 'KOTA TARAKAN', value: { id: '6571', name: 'KOTA TARAKAN', idprov: '65' } },
      { label: 'KOTA TASIKMALAYA', value: { id: '3278', name: 'KOTA TASIKMALAYA', idprov: '32' } },
      { label: 'KOTA TEBING TINGGI', value: { id: '1276', name: 'KOTA TEBING TINGGI', idprov: '12' } },
      { label: 'KOTA TEGAL', value: { id: '3376', name: 'KOTA TEGAL', idprov: '33' } },
      { label: 'KOTA TERNATE', value: { id: '8271', name: 'KOTA TERNATE', idprov: '82' } },
      { label: 'KOTA TIDORE KEPULAUAN', value: { id: '8272', name: 'KOTA TIDORE KEPULAUAN', idprov: '82' } },
      { label: 'KOTA TOMOHON', value: { id: '7173', name: 'KOTA TOMOHON', idprov: '71' } },
      { label: 'KOTA TUAL', value: { id: '8172', name: 'KOTA TUAL', idprov: '81' } },
      { label: 'KOTA YOGYAKARTA', value: { id: '3471', name: 'KOTA YOGYAKARTA', idprov: '34' } },
    ]

    const country = [
      { label: 'Afghanistan (+93)', value: { id: '237', name: 'Afghanistan', code: '93' } },
      { label: 'Albania (+355)', value: { id: '1', name: 'Albania', code: '355' } },
      { label: 'Algeria (+213)', value: { id: '2', name: 'Algeria', code: '213' } },
      { label: 'American Samoa (+1-684)', value: { id: '3', name: 'American Samoa', code: '1-684' } },
      { label: 'Andorra (+376)', value: { id: '4', name: 'Andorra', code: '376' } },
      { label: 'Angola (+244)', value: { id: '5', name: 'Angola', code: '244' } },
      { label: 'Anguilla (+1-264)', value: { id: '6', name: 'Anguilla', code: '1-264' } },
      { label: 'Antarctica (+672)', value: { id: '7', name: 'Antarctica', code: '672' } },
      { label: 'Antigua and Barbuda (+1-268)', value: { id: '8', name: 'Antigua and Barbuda', code: '1-268' } },
      { label: 'Argentina (+54)', value: { id: '9', name: 'Argentina', code: '54' } },
      { label: 'Armenia (+374)', value: { id: '10', name: 'Armenia', code: '374' } },
      { label: 'Aruba (+297)', value: { id: '11', name: 'Aruba', code: '297' } },
      { label: 'Australia (+61)', value: { id: '12', name: 'Australia', code: '61' } },
      { label: 'Austria (+43)', value: { id: '13', name: 'Austria', code: '43' } },
      { label: 'Azerbaijan (+994)', value: { id: '14', name: 'Azerbaijan', code: '994' } },
      { label: 'Bahamas (+1-242)', value: { id: '15', name: 'Bahamas', code: '1-242' } },
      { label: 'Bahrain (+973)', value: { id: '16', name: 'Bahrain', code: '973' } },
      { label: 'Bangladesh (+880)', value: { id: '17', name: 'Bangladesh', code: '880' } },
      { label: 'Barbados (+1-246)', value: { id: '18', name: 'Barbados', code: '1-246' } },
      { label: 'Belarus (+375)', value: { id: '19', name: 'Belarus', code: '375' } },
      { label: 'Belgium (+32)', value: { id: '20', name: 'Belgium', code: '32' } },
      { label: 'Belize (+501)', value: { id: '21', name: 'Belize', code: '501' } },
      { label: 'Benin (+229)', value: { id: '22', name: 'Benin', code: '229' } },
      { label: 'Bermuda (+1-441)', value: { id: '23', name: 'Bermuda', code: '1-441' } },
      { label: 'Bhutan (+975)', value: { id: '24', name: 'Bhutan', code: '975' } },
      { label: 'Bolivia (+591)', value: { id: '25', name: 'Bolivia', code: '591' } },
      { label: 'Bosnia and Herzegovina (+387)', value: { id: '26', name: 'Bosnia and Herzegovina', code: '387' } },
      { label: 'Botswana (+267)', value: { id: '27', name: 'Botswana', code: '267' } },
      { label: 'Brazil (+55)', value: { id: '28', name: 'Brazil', code: '55' } },
      { label: 'British Indian Ocean Territory (+246)', value: { id: '29', name: 'British Indian Ocean Territory', code: '246' } },
      { label: 'British Virgin Islands (+1-284)', value: { id: '30', name: 'British Virgin Islands', code: '1-284' } },
      { label: 'Brunei (+673)', value: { id: '31', name: 'Brunei', code: '673' } },
      { label: 'Bulgaria (+359)', value: { id: '32', name: 'Bulgaria', code: '359' } },
      { label: 'Burkina Faso (+226)', value: { id: '33', name: 'Burkina Faso', code: '226' } },
      { label: 'Burundi (+257)', value: { id: '34', name: 'Burundi', code: '257' } },
      { label: 'Cambodia (+855)', value: { id: '35', name: 'Cambodia', code: '855' } },
      { label: 'Cameroon (+237)', value: { id: '36', name: 'Cameroon', code: '237' } },
      { label: 'Canada (+1)', value: { id: '37', name: 'Canada', code: '1' } },
      { label: 'Cape Verde (+238)', value: { id: '38', name: 'Cape Verde', code: '238' } },
      { label: 'Cayman Islands (+1-345)', value: { id: '39', name: 'Cayman Islands', code: '1-345' } },
      { label: 'Central African Republic (+236)', value: { id: '40', name: 'Central African Republic', code: '236' } },
      { label: 'Chad (+235)', value: { id: '41', name: 'Chad', code: '235' } },
      { label: 'Chile (+56)', value: { id: '42', name: 'Chile', code: '56' } },
      { label: 'China (+86)', value: { id: '43', name: 'China', code: '86' } },
      { label: 'Christmas Island (+61)', value: { id: '44', name: 'Christmas Island', code: '61' } },
      { label: 'Cocos Islands (+61)', value: { id: '45', name: 'Cocos Islands', code: '61' } },
      { label: 'Colombia (+57)', value: { id: '46', name: 'Colombia', code: '57' } },
      { label: 'Comoros (+269)', value: { id: '47', name: 'Comoros', code: '269' } },
      { label: 'Cook Islands (+682)', value: { id: '48', name: 'Cook Islands', code: '682' } },
      { label: 'Costa Rica (+506)', value: { id: '49', name: 'Costa Rica', code: '506' } },
      { label: 'Croatia (+385)', value: { id: '50', name: 'Croatia', code: '385' } },
      { label: 'Cuba (+53)', value: { id: '51', name: 'Cuba', code: '53' } },
      { label: 'Curacao (+599)', value: { id: '52', name: 'Curacao', code: '599' } },
      { label: 'Cyprus (+357)', value: { id: '53', name: 'Cyprus', code: '357' } },
      { label: 'Czech Republic (+420)', value: { id: '54', name: 'Czech Republic', code: '420' } },
      { label: 'Democratic Republic of the Congo (+243)', value: { id: '55', name: 'Democratic Republic of the Congo', code: '243' } },
      { label: 'Denmark (+45)', value: { id: '56', name: 'Denmark', code: '45' } },
      { label: 'Djibouti (+253)', value: { id: '57', name: 'Djibouti', code: '253' } },
      { label: 'Dominica (+1-767)', value: { id: '58', name: 'Dominica', code: '1-767' } },
      { label: 'East Timor (+670)', value: { id: '59', name: 'East Timor', code: '670' } },
      { label: 'Ecuador (+593)', value: { id: '60', name: 'Ecuador', code: '593' } },
      { label: 'Egypt (+20)', value: { id: '61', name: 'Egypt', code: '20' } },
      { label: 'El Salvador (+503)', value: { id: '62', name: 'El Salvador', code: '503' } },
      { label: 'Equatorial Guinea (+240)', value: { id: '63', name: 'Equatorial Guinea', code: '240' } },
      { label: 'Eritrea (+291)', value: { id: '64', name: 'Eritrea', code: '291' } },
      { label: 'Estonia (+372)', value: { id: '65', name: 'Estonia', code: '372' } },
      { label: 'Ethiopia (+251)', value: { id: '66', name: 'Ethiopia', code: '251' } },
      { label: 'Falkland Islands (+500)', value: { id: '67', name: 'Falkland Islands', code: '500' } },
      { label: 'Faroe Islands (+298)', value: { id: '68', name: 'Faroe Islands', code: '298' } },
      { label: 'Fiji (+679)', value: { id: '69', name: 'Fiji', code: '679' } },
      { label: 'Finland (+358)', value: { id: '70', name: 'Finland', code: '358' } },
      { label: 'France (+33)', value: { id: '71', name: 'France', code: '33' } },
      { label: 'French Polynesia (+689)', value: { id: '72', name: 'French Polynesia', code: '689' } },
      { label: 'Gabon (+241)', value: { id: '73', name: 'Gabon', code: '241' } },
      { label: 'Gambia (+220)', value: { id: '74', name: 'Gambia', code: '220' } },
      { label: 'Georgia (+995)', value: { id: '75', name: 'Georgia', code: '995' } },
      { label: 'Germany (+49)', value: { id: '76', name: 'Germany', code: '49' } },
      { label: 'Ghana (+233)', value: { id: '77', name: 'Ghana', code: '233' } },
      { label: 'Gibraltar (+350)', value: { id: '78', name: 'Gibraltar', code: '350' } },
      { label: 'Greece (+30)', value: { id: '79', name: 'Greece', code: '30' } },
      { label: 'Greenland (+299)', value: { id: '80', name: 'Greenland', code: '299' } },
      { label: 'Grenada (+1-473)', value: { id: '81', name: 'Grenada', code: '1-473' } },
      { label: 'Guam (+1-671)', value: { id: '82', name: 'Guam', code: '1-671' } },
      { label: 'Guatemala (+502)', value: { id: '83', name: 'Guatemala', code: '502' } },
      { label: 'Guernsey (+44-1481)', value: { id: '84', name: 'Guernsey', code: '44-1481' } },
      { label: 'Guinea (+224)', value: { id: '85', name: 'Guinea', code: '224' } },
      { label: 'Guinea-Bissau (+245)', value: { id: '86', name: 'Guinea-Bissau', code: '245' } },
      { label: 'Guyana (+592)', value: { id: '87', name: 'Guyana', code: '592' } },
      { label: 'Haiti (+509)', value: { id: '88', name: 'Haiti', code: '509' } },
      { label: 'Honduras (+504)', value: { id: '89', name: 'Honduras', code: '504' } },
      { label: 'Hong Kong (+852)', value: { id: '90', name: 'Hong Kong', code: '852' } },
      { label: 'Hungary (+36)', value: { id: '91', name: 'Hungary', code: '36' } },
      { label: 'Iceland (+354)', value: { id: '92', name: 'Iceland', code: '354' } },
      { label: 'India (+91)', value: { id: '93', name: 'India', code: '91' } },
      { label: 'Indonesia (+62)', value: { id: '94', name: 'Indonesia', code: '62' } },
      { label: 'Iran (+98)', value: { id: '95', name: 'Iran', code: '98' } },
      { label: 'Iraq (+964)', value: { id: '96', name: 'Iraq', code: '964' } },
      { label: 'Ireland (+353)', value: { id: '97', name: 'Ireland', code: '353' } },
      { label: 'Israel (+972)', value: { id: '98', name: 'Israel', code: '972' } },
      { label: 'Italy (+39)', value: { id: '99', name: 'Italy', code: '39' } },
      { label: 'Ivory Coast (+225)', value: { id: '100', name: 'Ivory Coast', code: '225' } },
      { label: 'Jamaica (+1-876)', value: { id: '101', name: 'Jamaica', code: '1-876' } },
      { label: 'Japan (+81)', value: { id: '102', name: 'Japan', code: '81' } },
      { label: 'Jersey (+44-1534)', value: { id: '103', name: 'Jersey', code: '44-1534' } },
      { label: 'Jordan (+962)', value: { id: '104', name: 'Jordan', code: '962' } },
      { label: 'Kazakhstan (+7)', value: { id: '105', name: 'Kazakhstan', code: '7' } },
      { label: 'Kenya (+254)', value: { id: '106', name: 'Kenya', code: '254' } },
      { label: 'Kiribati (+686)', value: { id: '107', name: 'Kiribati', code: '686' } },
      { label: 'Kosovo (+383)', value: { id: '108', name: 'Kosovo', code: '383' } },
      { label: 'Kuwait (+965)', value: { id: '109', name: 'Kuwait', code: '965' } },
      { label: 'Kyrgyzstan (+996)', value: { id: '110', name: 'Kyrgyzstan', code: '996' } },
      { label: 'Laos (+856)', value: { id: '111', name: 'Laos', code: '856' } },
      { label: 'Latvia (+371)', value: { id: '112', name: 'Latvia', code: '371' } },
      { label: 'Lebanon (+961)', value: { id: '113', name: 'Lebanon', code: '961' } },
      { label: 'Lesotho (+266)', value: { id: '114', name: 'Lesotho', code: '266' } },
      { label: 'Liberia (+231)', value: { id: '115', name: 'Liberia', code: '231' } },
      { label: 'Libya (+218)', value: { id: '116', name: 'Libya', code: '218' } },
      { label: 'Liechtenstein (+423)', value: { id: '117', name: 'Liechtenstein', code: '423' } },
      { label: 'Lithuania (+370)', value: { id: '118', name: 'Lithuania', code: '370' } },
      { label: 'Luxembourg (+352)', value: { id: '119', name: 'Luxembourg', code: '352' } },
      { label: 'Macau (+853)', value: { id: '120', name: 'Macau', code: '853' } },
      { label: 'Macedonia (+389)', value: { id: '121', name: 'Macedonia', code: '389' } },
      { label: 'Madagascar (+261)', value: { id: '122', name: 'Madagascar', code: '261' } },
      { label: 'Malawi (+265)', value: { id: '123', name: 'Malawi', code: '265' } },
      { label: 'Malaysia (+60)', value: { id: '124', name: 'Malaysia', code: '60' } },
      { label: 'Maldives (+960)', value: { id: '125', name: 'Maldives', code: '960' } },
      { label: 'Mali (+223)', value: { id: '126', name: 'Mali', code: '223' } },
      { label: 'Malta (+356)', value: { id: '127', name: 'Malta', code: '356' } },
      { label: 'Marshall Islands (+692)', value: { id: '128', name: 'Marshall Islands', code: '692' } },
      { label: 'Mauritania (+222)', value: { id: '129', name: 'Mauritania', code: '222' } },
      { label: 'Mauritius (+230)', value: { id: '130', name: 'Mauritius', code: '230' } },
      { label: 'Mayotte (+262)', value: { id: '131', name: 'Mayotte', code: '262' } },
      { label: 'Mexico (+52)', value: { id: '132', name: 'Mexico', code: '52' } },
      { label: 'Micronesia (+691)', value: { id: '133', name: 'Micronesia', code: '691' } },
      { label: 'Moldova (+373)', value: { id: '134', name: 'Moldova', code: '373' } },
      { label: 'Monaco (+377)', value: { id: '135', name: 'Monaco', code: '377' } },
      { label: 'Mongolia (+976)', value: { id: '136', name: 'Mongolia', code: '976' } },
      { label: 'Montenegro (+382)', value: { id: '137', name: 'Montenegro', code: '382' } },
      { label: 'Montserrat (+1-664)', value: { id: '138', name: 'Montserrat', code: '1-664' } },
      { label: 'Morocco (+212)', value: { id: '139', name: 'Morocco', code: '212' } },
      { label: 'Mozambique (+258)', value: { id: '140', name: 'Mozambique', code: '258' } },
      { label: 'Myanmar (+95)', value: { id: '141', name: 'Myanmar', code: '95' } },
      { label: 'Namibia (+264)', value: { id: '142', name: 'Namibia', code: '264' } },
      { label: 'Nauru (+674)', value: { id: '143', name: 'Nauru', code: '674' } },
      { label: 'Nepal (+977)', value: { id: '144', name: 'Nepal', code: '977' } },
      { label: 'Netherlands (+31)', value: { id: '145', name: 'Netherlands', code: '31' } },
      { label: 'Netherlands Antilles (+599)', value: { id: '146', name: 'Netherlands Antilles', code: '599' } },
      { label: 'New Caledonia (+687)', value: { id: '147', name: 'New Caledonia', code: '687' } },
      { label: 'New Zealand (+64)', value: { id: '148', name: 'New Zealand', code: '64' } },
      { label: 'Nicaragua (+505)', value: { id: '149', name: 'Nicaragua', code: '505' } },
      { label: 'Niger (+227)', value: { id: '150', name: 'Niger', code: '227' } },
      { label: 'Nigeria (+234)', value: { id: '151', name: 'Nigeria', code: '234' } },
      { label: 'Niue (+683)', value: { id: '152', name: 'Niue', code: '683' } },
      { label: 'North Korea (+850)', value: { id: '153', name: 'North Korea', code: '850' } },
      { label: 'Northern Mariana Islands (+1-670)', value: { id: '154', name: 'Northern Mariana Islands', code: '1-670' } },
      { label: 'Norway (+47)', value: { id: '155', name: 'Norway', code: '47' } },
      { label: 'Oman (+968)', value: { id: '156', name: 'Oman', code: '968' } },
      { label: 'Pakistan (+92)', value: { id: '157', name: 'Pakistan', code: '92' } },
      { label: 'Palau (+680)', value: { id: '158', name: 'Palau', code: '680' } },
      { label: 'Palestine (+970)', value: { id: '159', name: 'Palestine', code: '970' } },
      { label: 'Panama (+507)', value: { id: '160', name: 'Panama', code: '507' } },
      { label: 'Papua New Guinea (+675)', value: { id: '161', name: 'Papua New Guinea', code: '675' } },
      { label: 'Paraguay (+595)', value: { id: '162', name: 'Paraguay', code: '595' } },
      { label: 'Peru (+51)', value: { id: '163', name: 'Peru', code: '51' } },
      { label: 'Philippines (+63)', value: { id: '164', name: 'Philippines', code: '63' } },
      { label: 'Pitcairn (+64)', value: { id: '165', name: 'Pitcairn', code: '64' } },
      { label: 'Poland (+48)', value: { id: '166', name: 'Poland', code: '48' } },
      { label: 'Portugal (+351)', value: { id: '167', name: 'Portugal', code: '351' } },
      { label: 'Qatar (+974)', value: { id: '168', name: 'Qatar', code: '974' } },
      { label: 'Republic of the Congo (+242)', value: { id: '169', name: 'Republic of the Congo', code: '242' } },
      { label: 'Reunion (+262)', value: { id: '170', name: 'Reunion', code: '262' } },
      { label: 'Romania (+40)', value: { id: '171', name: 'Romania', code: '40' } },
      { label: 'Russia (+7)', value: { id: '172', name: 'Russia', code: '7' } },
      { label: 'Rwanda (+250)', value: { id: '173', name: 'Rwanda', code: '250' } },
      { label: 'Saint Barthelemy (+590)', value: { id: '174', name: 'Saint Barthelemy', code: '590' } },
      { label: 'Saint Helena (+290)', value: { id: '175', name: 'Saint Helena', code: '290' } },
      { label: 'Saint Kitts and Nevis (+1-869)', value: { id: '176', name: 'Saint Kitts and Nevis', code: '1-869' } },
      { label: 'Saint Lucia (+1-758)', value: { id: '177', name: 'Saint Lucia', code: '1-758' } },
      { label: 'Saint Martin (+590)', value: { id: '178', name: 'Saint Martin', code: '590' } },
      { label: 'Saint Pierre and Miquelon (+508)', value: { id: '179', name: 'Saint Pierre and Miquelon', code: '508' } },
      { label: 'Saint Vincent and the Grenadines (+1-784)', value: { id: '180', name: 'Saint Vincent and the Grenadines', code: '1-784' } },
      { label: 'Samoa (+685)', value: { id: '181', name: 'Samoa', code: '685' } },
      { label: 'San Marino (+378)', value: { id: '182', name: 'San Marino', code: '378' } },
      { label: 'Sao Tome and Principe (+239)', value: { id: '183', name: 'Sao Tome and Principe', code: '239' } },
      { label: 'Saudi Arabia (+966)', value: { id: '184', name: 'Saudi Arabia', code: '966' } },
      { label: 'Senegal (+221)', value: { id: '185', name: 'Senegal', code: '221' } },
      { label: 'Serbia (+381)', value: { id: '186', name: 'Serbia', code: '381' } },
      { label: 'Seychelles (+248)', value: { id: '187', name: 'Seychelles', code: '248' } },
      { label: 'Sierra Leone (+232)', value: { id: '188', name: 'Sierra Leone', code: '232' } },
      { label: 'Singapore (+65)', value: { id: '189', name: 'Singapore', code: '65' } },
      { label: 'Sint Maarten (+1-721)', value: { id: '190', name: 'Sint Maarten', code: '1-721' } },
      { label: 'Slovakia (+421)', value: { id: '191', name: 'Slovakia', code: '421' } },
      { label: 'Slovenia (+386)', value: { id: '192', name: 'Slovenia', code: '386' } },
      { label: 'Solomon Islands (+677)', value: { id: '193', name: 'Solomon Islands', code: '677' } },
      { label: 'Somalia (+252)', value: { id: '194', name: 'Somalia', code: '252' } },
      { label: 'South Africa (+27)', value: { id: '195', name: 'South Africa', code: '27' } },
      { label: 'South Korea (+82)', value: { id: '196', name: 'South Korea', code: '82' } },
      { label: 'South Sudan (+211)', value: { id: '197', name: 'South Sudan', code: '211' } },
      { label: 'Spain (+34)', value: { id: '198', name: 'Spain', code: '34' } },
      { label: 'Sri Lanka (+94)', value: { id: '199', name: 'Sri Lanka', code: '94' } },
      { label: 'Sudan (+249)', value: { id: '200', name: 'Sudan', code: '249' } },
      { label: 'Suriname (+597)', value: { id: '201', name: 'Suriname', code: '597' } },
      { label: 'Svalbard and Jan Mayen (+47)', value: { id: '202', name: 'Svalbard and Jan Mayen', code: '47' } },
      { label: 'Swaziland (+268)', value: { id: '203', name: 'Swaziland', code: '268' } },
      { label: 'Sweden (+46)', value: { id: '204', name: 'Sweden', code: '46' } },
      { label: 'Switzerland (+41)', value: { id: '205', name: 'Switzerland', code: '41' } },
      { label: 'Syria (+963)', value: { id: '206', name: 'Syria', code: '963' } },
      { label: 'Taiwan (+886)', value: { id: '207', name: 'Taiwan', code: '886' } },
      { label: 'Tajikistan (+992)', value: { id: '208', name: 'Tajikistan', code: '992' } },
      { label: 'Tanzania (+255)', value: { id: '209', name: 'Tanzania', code: '255' } },
      { label: 'Thailand (+66)', value: { id: '210', name: 'Thailand', code: '66' } },
      { label: 'Togo (+228)', value: { id: '211', name: 'Togo', code: '228' } },
      { label: 'Tokelau (+690)', value: { id: '212', name: 'Tokelau', code: '690' } },
      { label: 'Tonga (+676)', value: { id: '213', name: 'Tonga', code: '676' } },
      { label: 'Trinidad and Tobago (+1-868)', value: { id: '214', name: 'Trinidad and Tobago', code: '1-868' } },
      { label: 'Tunisia (+216)', value: { id: '215', name: 'Tunisia', code: '216' } },
      { label: 'Turkey (+90)', value: { id: '216', name: 'Turkey', code: '90' } },
      { label: 'Turkmenistan (+993)', value: { id: '217', name: 'Turkmenistan', code: '993' } },
      { label: 'Turks and Caicos Islands (+1-649)', value: { id: '218', name: 'Turks and Caicos Islands', code: '1-649' } },
      { label: 'Tuvalu (+688)', value: { id: '219', name: 'Tuvalu', code: '688' } },
      { label: 'U.S. Virgin Islands (+1-340)', value: { id: '220', name: 'U.S. Virgin Islands', code: '1-340' } },
      { label: 'Uganda (+256)', value: { id: '221', name: 'Uganda', code: '256' } },
      { label: 'Ukraine (+380)', value: { id: '222', name: 'Ukraine', code: '380' } },
      { label: 'United Arab Emirates (+971)', value: { id: '223', name: 'United Arab Emirates', code: '971' } },
      { label: 'United Kingdom (+44)', value: { id: '224', name: 'United Kingdom', code: '44' } },
      { label: 'United States (+1)', value: { id: '225', name: 'United States', code: '1' } },
      { label: 'Uruguay (+598)', value: { id: '226', name: 'Uruguay', code: '598' } },
      { label: 'Uzbekistan (+998)', value: { id: '227', name: 'Uzbekistan', code: '998' } },
      { label: 'Vanuatu (+678)', value: { id: '228', name: 'Vanuatu', code: '678' } },
      { label: 'Vatican (+379)', value: { id: '229', name: 'Vatican', code: '379' } },
      { label: 'Venezuela (+58)', value: { id: '230', name: 'Venezuela', code: '58' } },
      { label: 'Vietnam (+84)', value: { id: '231', name: 'Vietnam', code: '84' } },
      { label: 'Wallis and Futuna (+681)', value: { id: '232', name: 'Wallis and Futuna', code: '681' } },
      { label: 'Western Sahara (+212)', value: { id: '233', name: 'Western Sahara', code: '212' } },
      { label: 'Yemen (+967)', value: { id: '234', name: 'Yemen', code: '967' } },
      { label: 'Zambia (+260)', value: { id: '235', name: 'Zambia', code: '260' } },
      { label: 'Zimbabwe (+263)', value: { id: '236', name: 'Zimbabwe', code: '263' } }
    ]

    return null;
  }

}
