import { SelectItem } from 'primeng/api';

export const Country: SelectItem[] = [
  { label: 'Afghanistan (+93)', value: { id: '237', name: 'Afghanistan', code: '93' } },
  { label: 'Albania (+355)', value: { id: '1', name: 'Albania', code: '355' } },
  { label: 'Algeria (+213)', value: { id: '2', name: 'Algeria', code: '213' } },
  { label: 'American Samoa (+1-684)', value: { id: '3', name: 'American Samoa', code: '1-684' } },
  { label: 'Andorra (+376)', value: { id: '4', name: 'Andorra', code: '376' } },
  { label: 'Angola (+244)', value: { id: '5', name: 'Angola', code: '244' } },
  { label: 'Anguilla (+1-264)', value: { id: '6', name: 'Anguilla', code: '1-264' } },
  { label: 'Antarctica (+672)', value: { id: '7', name: 'Antarctica', code: '672' } },
  { label: 'Antigua and Barbuda (+1-268)', value: { id: '8', name: 'Antigua and Barbuda', code: '1-268' } },
  { label: 'Argentina (+54)', value: { id: '9', name: 'Argentina', code: '54' } },
  { label: 'Armenia (+374)', value: { id: '10', name: 'Armenia', code: '374' } },
  { label: 'Aruba (+297)', value: { id: '11', name: 'Aruba', code: '297' } },
  { label: 'Australia (+61)', value: { id: '12', name: 'Australia', code: '61' } },
  { label: 'Austria (+43)', value: { id: '13', name: 'Austria', code: '43' } },
  { label: 'Azerbaijan (+994)', value: { id: '14', name: 'Azerbaijan', code: '994' } },
  { label: 'Bahamas (+1-242)', value: { id: '15', name: 'Bahamas', code: '1-242' } },
  { label: 'Bahrain (+973)', value: { id: '16', name: 'Bahrain', code: '973' } },
  { label: 'Bangladesh (+880)', value: { id: '17', name: 'Bangladesh', code: '880' } },
  { label: 'Barbados (+1-246)', value: { id: '18', name: 'Barbados', code: '1-246' } },
  { label: 'Belarus (+375)', value: { id: '19', name: 'Belarus', code: '375' } },
  { label: 'Belgium (+32)', value: { id: '20', name: 'Belgium', code: '32' } },
  { label: 'Belize (+501)', value: { id: '21', name: 'Belize', code: '501' } },
  { label: 'Benin (+229)', value: { id: '22', name: 'Benin', code: '229' } },
  { label: 'Bermuda (+1-441)', value: { id: '23', name: 'Bermuda', code: '1-441' } },
  { label: 'Bhutan (+975)', value: { id: '24', name: 'Bhutan', code: '975' } },
  { label: 'Bolivia (+591)', value: { id: '25', name: 'Bolivia', code: '591' } },
  { label: 'Bosnia and Herzegovina (+387)', value: { id: '26', name: 'Bosnia and Herzegovina', code: '387' } },
  { label: 'Botswana (+267)', value: { id: '27', name: 'Botswana', code: '267' } },
  { label: 'Brazil (+55)', value: { id: '28', name: 'Brazil', code: '55' } },
  { label: 'British Indian Ocean Territory (+246)', value: { id: '29', name: 'British Indian Ocean Territory', code: '246' } },
  { label: 'British Virgin Islands (+1-284)', value: { id: '30', name: 'British Virgin Islands', code: '1-284' } },
  { label: 'Brunei (+673)', value: { id: '31', name: 'Brunei', code: '673' } },
  { label: 'Bulgaria (+359)', value: { id: '32', name: 'Bulgaria', code: '359' } },
  { label: 'Burkina Faso (+226)', value: { id: '33', name: 'Burkina Faso', code: '226' } },
  { label: 'Burundi (+257)', value: { id: '34', name: 'Burundi', code: '257' } },
  { label: 'Cambodia (+855)', value: { id: '35', name: 'Cambodia', code: '855' } },
  { label: 'Cameroon (+237)', value: { id: '36', name: 'Cameroon', code: '237' } },
  { label: 'Canada (+1)', value: { id: '37', name: 'Canada', code: '1' } },
  { label: 'Cape Verde (+238)', value: { id: '38', name: 'Cape Verde', code: '238' } },
  { label: 'Cayman Islands (+1-345)', value: { id: '39', name: 'Cayman Islands', code: '1-345' } },
  { label: 'Central African Republic (+236)', value: { id: '40', name: 'Central African Republic', code: '236' } },
  { label: 'Chad (+235)', value: { id: '41', name: 'Chad', code: '235' } },
  { label: 'Chile (+56)', value: { id: '42', name: 'Chile', code: '56' } },
  { label: 'China (+86)', value: { id: '43', name: 'China', code: '86' } },
  { label: 'Christmas Island (+61)', value: { id: '44', name: 'Christmas Island', code: '61' } },
  { label: 'Cocos Islands (+61)', value: { id: '45', name: 'Cocos Islands', code: '61' } },
  { label: 'Colombia (+57)', value: { id: '46', name: 'Colombia', code: '57' } },
  { label: 'Comoros (+269)', value: { id: '47', name: 'Comoros', code: '269' } },
  { label: 'Cook Islands (+682)', value: { id: '48', name: 'Cook Islands', code: '682' } },
  { label: 'Costa Rica (+506)', value: { id: '49', name: 'Costa Rica', code: '506' } },
  { label: 'Croatia (+385)', value: { id: '50', name: 'Croatia', code: '385' } },
  { label: 'Cuba (+53)', value: { id: '51', name: 'Cuba', code: '53' } },
  { label: 'Curacao (+599)', value: { id: '52', name: 'Curacao', code: '599' } },
  { label: 'Cyprus (+357)', value: { id: '53', name: 'Cyprus', code: '357' } },
  { label: 'Czech Republic (+420)', value: { id: '54', name: 'Czech Republic', code: '420' } },
  { label: 'Democratic Republic of the Congo (+243)', value: { id: '55', name: 'Democratic Republic of the Congo', code: '243' } },
  { label: 'Denmark (+45)', value: { id: '56', name: 'Denmark', code: '45' } },
  { label: 'Djibouti (+253)', value: { id: '57', name: 'Djibouti', code: '253' } },
  { label: 'Dominica (+1-767)', value: { id: '58', name: 'Dominica', code: '1-767' } },
  { label: 'East Timor (+670)', value: { id: '59', name: 'East Timor', code: '670' } },
  { label: 'Ecuador (+593)', value: { id: '60', name: 'Ecuador', code: '593' } },
  { label: 'Egypt (+20)', value: { id: '61', name: 'Egypt', code: '20' } },
  { label: 'El Salvador (+503)', value: { id: '62', name: 'El Salvador', code: '503' } },
  { label: 'Equatorial Guinea (+240)', value: { id: '63', name: 'Equatorial Guinea', code: '240' } },
  { label: 'Eritrea (+291)', value: { id: '64', name: 'Eritrea', code: '291' } },
  { label: 'Estonia (+372)', value: { id: '65', name: 'Estonia', code: '372' } },
  { label: 'Ethiopia (+251)', value: { id: '66', name: 'Ethiopia', code: '251' } },
  { label: 'Falkland Islands (+500)', value: { id: '67', name: 'Falkland Islands', code: '500' } },
  { label: 'Faroe Islands (+298)', value: { id: '68', name: 'Faroe Islands', code: '298' } },
  { label: 'Fiji (+679)', value: { id: '69', name: 'Fiji', code: '679' } },
  { label: 'Finland (+358)', value: { id: '70', name: 'Finland', code: '358' } },
  { label: 'France (+33)', value: { id: '71', name: 'France', code: '33' } },
  { label: 'French Polynesia (+689)', value: { id: '72', name: 'French Polynesia', code: '689' } },
  { label: 'Gabon (+241)', value: { id: '73', name: 'Gabon', code: '241' } },
  { label: 'Gambia (+220)', value: { id: '74', name: 'Gambia', code: '220' } },
  { label: 'Georgia (+995)', value: { id: '75', name: 'Georgia', code: '995' } },
  { label: 'Germany (+49)', value: { id: '76', name: 'Germany', code: '49' } },
  { label: 'Ghana (+233)', value: { id: '77', name: 'Ghana', code: '233' } },
  { label: 'Gibraltar (+350)', value: { id: '78', name: 'Gibraltar', code: '350' } },
  { label: 'Greece (+30)', value: { id: '79', name: 'Greece', code: '30' } },
  { label: 'Greenland (+299)', value: { id: '80', name: 'Greenland', code: '299' } },
  { label: 'Grenada (+1-473)', value: { id: '81', name: 'Grenada', code: '1-473' } },
  { label: 'Guam (+1-671)', value: { id: '82', name: 'Guam', code: '1-671' } },
  { label: 'Guatemala (+502)', value: { id: '83', name: 'Guatemala', code: '502' } },
  { label: 'Guernsey (+44-1481)', value: { id: '84', name: 'Guernsey', code: '44-1481' } },
  { label: 'Guinea (+224)', value: { id: '85', name: 'Guinea', code: '224' } },
  { label: 'Guinea-Bissau (+245)', value: { id: '86', name: 'Guinea-Bissau', code: '245' } },
  { label: 'Guyana (+592)', value: { id: '87', name: 'Guyana', code: '592' } },
  { label: 'Haiti (+509)', value: { id: '88', name: 'Haiti', code: '509' } },
  { label: 'Honduras (+504)', value: { id: '89', name: 'Honduras', code: '504' } },
  { label: 'Hong Kong (+852)', value: { id: '90', name: 'Hong Kong', code: '852' } },
  { label: 'Hungary (+36)', value: { id: '91', name: 'Hungary', code: '36' } },
  { label: 'Iceland (+354)', value: { id: '92', name: 'Iceland', code: '354' } },
  { label: 'India (+91)', value: { id: '93', name: 'India', code: '91' } },
  { label: 'Indonesia (+62)', value: { id: '94', name: 'Indonesia', code: '62' } },
  { label: 'Iran (+98)', value: { id: '95', name: 'Iran', code: '98' } },
  { label: 'Iraq (+964)', value: { id: '96', name: 'Iraq', code: '964' } },
  { label: 'Ireland (+353)', value: { id: '97', name: 'Ireland', code: '353' } },
  { label: 'Israel (+972)', value: { id: '98', name: 'Israel', code: '972' } },
  { label: 'Italy (+39)', value: { id: '99', name: 'Italy', code: '39' } },
  { label: 'Ivory Coast (+225)', value: { id: '100', name: 'Ivory Coast', code: '225' } },
  { label: 'Jamaica (+1-876)', value: { id: '101', name: 'Jamaica', code: '1-876' } },
  { label: 'Japan (+81)', value: { id: '102', name: 'Japan', code: '81' } },
  { label: 'Jersey (+44-1534)', value: { id: '103', name: 'Jersey', code: '44-1534' } },
  { label: 'Jordan (+962)', value: { id: '104', name: 'Jordan', code: '962' } },
  { label: 'Kazakhstan (+7)', value: { id: '105', name: 'Kazakhstan', code: '7' } },
  { label: 'Kenya (+254)', value: { id: '106', name: 'Kenya', code: '254' } },
  { label: 'Kiribati (+686)', value: { id: '107', name: 'Kiribati', code: '686' } },
  { label: 'Kosovo (+383)', value: { id: '108', name: 'Kosovo', code: '383' } },
  { label: 'Kuwait (+965)', value: { id: '109', name: 'Kuwait', code: '965' } },
  { label: 'Kyrgyzstan (+996)', value: { id: '110', name: 'Kyrgyzstan', code: '996' } },
  { label: 'Laos (+856)', value: { id: '111', name: 'Laos', code: '856' } },
  { label: 'Latvia (+371)', value: { id: '112', name: 'Latvia', code: '371' } },
  { label: 'Lebanon (+961)', value: { id: '113', name: 'Lebanon', code: '961' } },
  { label: 'Lesotho (+266)', value: { id: '114', name: 'Lesotho', code: '266' } },
  { label: 'Liberia (+231)', value: { id: '115', name: 'Liberia', code: '231' } },
  { label: 'Libya (+218)', value: { id: '116', name: 'Libya', code: '218' } },
  { label: 'Liechtenstein (+423)', value: { id: '117', name: 'Liechtenstein', code: '423' } },
  { label: 'Lithuania (+370)', value: { id: '118', name: 'Lithuania', code: '370' } },
  { label: 'Luxembourg (+352)', value: { id: '119', name: 'Luxembourg', code: '352' } },
  { label: 'Macau (+853)', value: { id: '120', name: 'Macau', code: '853' } },
  { label: 'Macedonia (+389)', value: { id: '121', name: 'Macedonia', code: '389' } },
  { label: 'Madagascar (+261)', value: { id: '122', name: 'Madagascar', code: '261' } },
  { label: 'Malawi (+265)', value: { id: '123', name: 'Malawi', code: '265' } },
  { label: 'Malaysia (+60)', value: { id: '124', name: 'Malaysia', code: '60' } },
  { label: 'Maldives (+960)', value: { id: '125', name: 'Maldives', code: '960' } },
  { label: 'Mali (+223)', value: { id: '126', name: 'Mali', code: '223' } },
  { label: 'Malta (+356)', value: { id: '127', name: 'Malta', code: '356' } },
  { label: 'Marshall Islands (+692)', value: { id: '128', name: 'Marshall Islands', code: '692' } },
  { label: 'Mauritania (+222)', value: { id: '129', name: 'Mauritania', code: '222' } },
  { label: 'Mauritius (+230)', value: { id: '130', name: 'Mauritius', code: '230' } },
  { label: 'Mayotte (+262)', value: { id: '131', name: 'Mayotte', code: '262' } },
  { label: 'Mexico (+52)', value: { id: '132', name: 'Mexico', code: '52' } },
  { label: 'Micronesia (+691)', value: { id: '133', name: 'Micronesia', code: '691' } },
  { label: 'Moldova (+373)', value: { id: '134', name: 'Moldova', code: '373' } },
  { label: 'Monaco (+377)', value: { id: '135', name: 'Monaco', code: '377' } },
  { label: 'Mongolia (+976)', value: { id: '136', name: 'Mongolia', code: '976' } },
  { label: 'Montenegro (+382)', value: { id: '137', name: 'Montenegro', code: '382' } },
  { label: 'Montserrat (+1-664)', value: { id: '138', name: 'Montserrat', code: '1-664' } },
  { label: 'Morocco (+212)', value: { id: '139', name: 'Morocco', code: '212' } },
  { label: 'Mozambique (+258)', value: { id: '140', name: 'Mozambique', code: '258' } },
  { label: 'Myanmar (+95)', value: { id: '141', name: 'Myanmar', code: '95' } },
  { label: 'Namibia (+264)', value: { id: '142', name: 'Namibia', code: '264' } },
  { label: 'Nauru (+674)', value: { id: '143', name: 'Nauru', code: '674' } },
  { label: 'Nepal (+977)', value: { id: '144', name: 'Nepal', code: '977' } },
  { label: 'Netherlands (+31)', value: { id: '145', name: 'Netherlands', code: '31' } },
  { label: 'Netherlands Antilles (+599)', value: { id: '146', name: 'Netherlands Antilles', code: '599' } },
  { label: 'New Caledonia (+687)', value: { id: '147', name: 'New Caledonia', code: '687' } },
  { label: 'New Zealand (+64)', value: { id: '148', name: 'New Zealand', code: '64' } },
  { label: 'Nicaragua (+505)', value: { id: '149', name: 'Nicaragua', code: '505' } },
  { label: 'Niger (+227)', value: { id: '150', name: 'Niger', code: '227' } },
  { label: 'Nigeria (+234)', value: { id: '151', name: 'Nigeria', code: '234' } },
  { label: 'Niue (+683)', value: { id: '152', name: 'Niue', code: '683' } },
  { label: 'North Korea (+850)', value: { id: '153', name: 'North Korea', code: '850' } },
  { label: 'Northern Mariana Islands (+1-670)', value: { id: '154', name: 'Northern Mariana Islands', code: '1-670' } },
  { label: 'Norway (+47)', value: { id: '155', name: 'Norway', code: '47' } },
  { label: 'Oman (+968)', value: { id: '156', name: 'Oman', code: '968' } },
  { label: 'Pakistan (+92)', value: { id: '157', name: 'Pakistan', code: '92' } },
  { label: 'Palau (+680)', value: { id: '158', name: 'Palau', code: '680' } },
  { label: 'Palestine (+970)', value: { id: '159', name: 'Palestine', code: '970' } },
  { label: 'Panama (+507)', value: { id: '160', name: 'Panama', code: '507' } },
  { label: 'Papua New Guinea (+675)', value: { id: '161', name: 'Papua New Guinea', code: '675' } },
  { label: 'Paraguay (+595)', value: { id: '162', name: 'Paraguay', code: '595' } },
  { label: 'Peru (+51)', value: { id: '163', name: 'Peru', code: '51' } },
  { label: 'Philippines (+63)', value: { id: '164', name: 'Philippines', code: '63' } },
  { label: 'Pitcairn (+64)', value: { id: '165', name: 'Pitcairn', code: '64' } },
  { label: 'Poland (+48)', value: { id: '166', name: 'Poland', code: '48' } },
  { label: 'Portugal (+351)', value: { id: '167', name: 'Portugal', code: '351' } },
  { label: 'Qatar (+974)', value: { id: '168', name: 'Qatar', code: '974' } },
  { label: 'Republic of the Congo (+242)', value: { id: '169', name: 'Republic of the Congo', code: '242' } },
  { label: 'Reunion (+262)', value: { id: '170', name: 'Reunion', code: '262' } },
  { label: 'Romania (+40)', value: { id: '171', name: 'Romania', code: '40' } },
  { label: 'Russia (+7)', value: { id: '172', name: 'Russia', code: '7' } },
  { label: 'Rwanda (+250)', value: { id: '173', name: 'Rwanda', code: '250' } },
  { label: 'Saint Barthelemy (+590)', value: { id: '174', name: 'Saint Barthelemy', code: '590' } },
  { label: 'Saint Helena (+290)', value: { id: '175', name: 'Saint Helena', code: '290' } },
  { label: 'Saint Kitts and Nevis (+1-869)', value: { id: '176', name: 'Saint Kitts and Nevis', code: '1-869' } },
  { label: 'Saint Lucia (+1-758)', value: { id: '177', name: 'Saint Lucia', code: '1-758' } },
  { label: 'Saint Martin (+590)', value: { id: '178', name: 'Saint Martin', code: '590' } },
  { label: 'Saint Pierre and Miquelon (+508)', value: { id: '179', name: 'Saint Pierre and Miquelon', code: '508' } },
  { label: 'Saint Vincent and the Grenadines (+1-784)', value: { id: '180', name: 'Saint Vincent and the Grenadines', code: '1-784' } },
  { label: 'Samoa (+685)', value: { id: '181', name: 'Samoa', code: '685' } },
  { label: 'San Marino (+378)', value: { id: '182', name: 'San Marino', code: '378' } },
  { label: 'Sao Tome and Principe (+239)', value: { id: '183', name: 'Sao Tome and Principe', code: '239' } },
  { label: 'Saudi Arabia (+966)', value: { id: '184', name: 'Saudi Arabia', code: '966' } },
  { label: 'Senegal (+221)', value: { id: '185', name: 'Senegal', code: '221' } },
  { label: 'Serbia (+381)', value: { id: '186', name: 'Serbia', code: '381' } },
  { label: 'Seychelles (+248)', value: { id: '187', name: 'Seychelles', code: '248' } },
  { label: 'Sierra Leone (+232)', value: { id: '188', name: 'Sierra Leone', code: '232' } },
  { label: 'Singapore (+65)', value: { id: '189', name: 'Singapore', code: '65' } },
  { label: 'Sint Maarten (+1-721)', value: { id: '190', name: 'Sint Maarten', code: '1-721' } },
  { label: 'Slovakia (+421)', value: { id: '191', name: 'Slovakia', code: '421' } },
  { label: 'Slovenia (+386)', value: { id: '192', name: 'Slovenia', code: '386' } },
  { label: 'Solomon Islands (+677)', value: { id: '193', name: 'Solomon Islands', code: '677' } },
  { label: 'Somalia (+252)', value: { id: '194', name: 'Somalia', code: '252' } },
  { label: 'South Africa (+27)', value: { id: '195', name: 'South Africa', code: '27' } },
  { label: 'South Korea (+82)', value: { id: '196', name: 'South Korea', code: '82' } },
  { label: 'South Sudan (+211)', value: { id: '197', name: 'South Sudan', code: '211' } },
  { label: 'Spain (+34)', value: { id: '198', name: 'Spain', code: '34' } },
  { label: 'Sri Lanka (+94)', value: { id: '199', name: 'Sri Lanka', code: '94' } },
  { label: 'Sudan (+249)', value: { id: '200', name: 'Sudan', code: '249' } },
  { label: 'Suriname (+597)', value: { id: '201', name: 'Suriname', code: '597' } },
  { label: 'Svalbard and Jan Mayen (+47)', value: { id: '202', name: 'Svalbard and Jan Mayen', code: '47' } },
  { label: 'Swaziland (+268)', value: { id: '203', name: 'Swaziland', code: '268' } },
  { label: 'Sweden (+46)', value: { id: '204', name: 'Sweden', code: '46' } },
  { label: 'Switzerland (+41)', value: { id: '205', name: 'Switzerland', code: '41' } },
  { label: 'Syria (+963)', value: { id: '206', name: 'Syria', code: '963' } },
  { label: 'Taiwan (+886)', value: { id: '207', name: 'Taiwan', code: '886' } },
  { label: 'Tajikistan (+992)', value: { id: '208', name: 'Tajikistan', code: '992' } },
  { label: 'Tanzania (+255)', value: { id: '209', name: 'Tanzania', code: '255' } },
  { label: 'Thailand (+66)', value: { id: '210', name: 'Thailand', code: '66' } },
  { label: 'Togo (+228)', value: { id: '211', name: 'Togo', code: '228' } },
  { label: 'Tokelau (+690)', value: { id: '212', name: 'Tokelau', code: '690' } },
  { label: 'Tonga (+676)', value: { id: '213', name: 'Tonga', code: '676' } },
  { label: 'Trinidad and Tobago (+1-868)', value: { id: '214', name: 'Trinidad and Tobago', code: '1-868' } },
  { label: 'Tunisia (+216)', value: { id: '215', name: 'Tunisia', code: '216' } },
  { label: 'Turkey (+90)', value: { id: '216', name: 'Turkey', code: '90' } },
  { label: 'Turkmenistan (+993)', value: { id: '217', name: 'Turkmenistan', code: '993' } },
  { label: 'Turks and Caicos Islands (+1-649)', value: { id: '218', name: 'Turks and Caicos Islands', code: '1-649' } },
  { label: 'Tuvalu (+688)', value: { id: '219', name: 'Tuvalu', code: '688' } },
  { label: 'U.S. Virgin Islands (+1-340)', value: { id: '220', name: 'U.S. Virgin Islands', code: '1-340' } },
  { label: 'Uganda (+256)', value: { id: '221', name: 'Uganda', code: '256' } },
  { label: 'Ukraine (+380)', value: { id: '222', name: 'Ukraine', code: '380' } },
  { label: 'United Arab Emirates (+971)', value: { id: '223', name: 'United Arab Emirates', code: '971' } },
  { label: 'United Kingdom (+44)', value: { id: '224', name: 'United Kingdom', code: '44' } },
  { label: 'United States (+1)', value: { id: '225', name: 'United States', code: '1' } },
  { label: 'Uruguay (+598)', value: { id: '226', name: 'Uruguay', code: '598' } },
  { label: 'Uzbekistan (+998)', value: { id: '227', name: 'Uzbekistan', code: '998' } },
  { label: 'Vanuatu (+678)', value: { id: '228', name: 'Vanuatu', code: '678' } },
  { label: 'Vatican (+379)', value: { id: '229', name: 'Vatican', code: '379' } },
  { label: 'Venezuela (+58)', value: { id: '230', name: 'Venezuela', code: '58' } },
  { label: 'Vietnam (+84)', value: { id: '231', name: 'Vietnam', code: '84' } },
  { label: 'Wallis and Futuna (+681)', value: { id: '232', name: 'Wallis and Futuna', code: '681' } },
  { label: 'Western Sahara (+212)', value: { id: '233', name: 'Western Sahara', code: '212' } },
  { label: 'Yemen (+967)', value: { id: '234', name: 'Yemen', code: '967' } },
  { label: 'Zambia (+260)', value: { id: '235', name: 'Zambia', code: '260' } },
  { label: 'Zimbabwe (+263)', value: { id: '236', name: 'Zimbabwe', code: '263' } }

]
